"use client";
import {useRef} from "react";import {Bold,Camera,Link2,Palette} from "lucide-react";import {EditorContent,useEditor,Mark,Extension,markInputRule} from "@tiptap/react";import {BubbleMenu} from "@tiptap/react/menus";import StarterKit from "@tiptap/starter-kit";import {TextStyle} from "@tiptap/extension-text-style";import Color from "@tiptap/extension-color";import FontFamily from "@tiptap/extension-font-family";import Link from "@tiptap/extension-link";import Image from "@tiptap/extension-image";

const sizes=[{label:"작게",value:"14px"},{label:"보통",value:"16px"},{label:"크게",value:"20px"},{label:"매우 크게",value:"28px"}],fonts=[{label:"기본 돋움",value:"sans-serif"},{label:"Pretendard",value:"Pretendard, sans-serif"},{label:"귀여운 손글씨",value:"KCC-Eunyoung, Nanum Pen Script, cursive"},{label:"바탕·명조",value:"MICEGothic, Batang, serif"}],colors=["#22242b","#e05f70","#e58a45","#3d9a72","#4382c4","#835fc1"];
const FontSize=Extension.create({name:"fontSize",addGlobalAttributes(){return[{types:["textStyle"],attributes:{fontSize:{default:null,parseHTML:element=>element.style.fontSize,renderHTML:attributes=>attributes.fontSize?{style:`font-size: ${attributes.fontSize}`}:{}}}}]}});
const Hashtag=Mark.create({name:"hashtag",inclusive:false,parseHTML(){return[{tag:"span[data-hashtag]"}]},renderHTML({HTMLAttributes}){return["span",{...HTMLAttributes,"data-hashtag":"true",class:"task-hashtag"},0]},addInputRules(){return[markInputRule({find:/(#[\p{L}\p{N}_-]+)$/u,type:this.type})]}});

export function TaskEditor({value,onChange,placeholder="내 생각과 조사한 내용을 자세히 적어 보세요."}:{value:string;onChange:(html:string)=>void;placeholder?:string}){const fileRef=useRef<HTMLInputElement>(null),editor=useEditor({immediatelyRender:false,extensions:[StarterKit,TextStyle,Color,FontFamily,FontSize,Hashtag,Link.configure({openOnClick:false,autolink:true,HTMLAttributes:{target:"_blank",rel:"noopener noreferrer"}}),Image.configure({allowBase64:true,HTMLAttributes:{class:"task-editor-image"}})],content:value||"",editorProps:{attributes:{class:"task-editor-content",role:"textbox","aria-label":"과제 내용 편집기","data-placeholder":placeholder}},onUpdate:({editor})=>onChange(editor.getHTML())});
 if(!editor)return <div className="task-editor-loading">에디터를 준비하고 있어요…</div>;
 function setSize(fontSize:string){editor.chain().focus().setMark("textStyle",{fontSize}).run()}function addLink(){const previous=editor.getAttributes("link").href??"",url=window.prompt("연결할 주소를 입력하세요.",previous);if(url===null)return;if(!url){editor.chain().focus().extendMarkRange("link").unsetLink().run();return}const safe=/^https?:\/\//i.test(url)?url:`https://${url}`;editor.chain().focus().extendMarkRange("link").setLink({href:safe}).run()}function addImage(file?:File){if(!file||!file.type.startsWith("image/"))return;const reader=new FileReader();reader.onload=()=>editor.chain().focus().setImage({src:String(reader.result),alt:file.name,title:file.name}).run();reader.readAsDataURL(file)}
 return <div className="task-editor"><div className="task-editor-toolbar"><select aria-label="글꼴 선택" value={editor.getAttributes("textStyle").fontFamily??"sans-serif"} onChange={event=>editor.chain().focus().setFontFamily(event.target.value).run()}>{fonts.map(font=><option key={font.value} value={font.value}>{font.label}</option>)}</select><select aria-label="글자 크기" value={editor.getAttributes("textStyle").fontSize??"16px"} onChange={event=>setSize(event.target.value)}>{sizes.map(size=><option key={size.value} value={size.value}>{size.label}</option>)}</select><button type="button" className={editor.isActive("bold")?"active":""} onClick={()=>editor.chain().focus().toggleBold().run()} title="굵게"><Bold/><span>굵게</span></button><div className="task-color-picker"><Palette/><span>글자 색</span>{colors.map(color=><button type="button" key={color} style={{backgroundColor:color}} className={editor.isActive("textStyle",{color})?"active":""} onClick={()=>editor.chain().focus().setColor(color).run()} aria-label={`${color} 글자색`}/>)}</div><button type="button" onClick={()=>fileRef.current?.click()}><Camera/><span>사진</span></button><button type="button" className={editor.isActive("link")?"active":""} onClick={addLink}><Link2/><span>링크</span></button><input ref={fileRef} hidden type="file" accept="image/*" onChange={event=>addImage(event.target.files?.[0])}/></div>
 <EditorContent editor={editor}/><BubbleMenu editor={editor} shouldShow={({editor})=>!editor.state.selection.empty}><div className="task-bubble-menu"><button type="button" className={editor.isActive("bold")?"active":""} onClick={()=>editor.chain().focus().toggleBold().run()}><Bold/></button>{sizes.map(size=><button type="button" key={size.value} onClick={()=>setSize(size.value)}>{size.label}</button>)}{colors.map(color=><button type="button" className="bubble-color" key={color} style={{backgroundColor:color}} onClick={()=>editor.chain().focus().setColor(color).run()}/>)}</div></BubbleMenu></div>}
