"use client";
import { useState,useTransition } from "react";
import { ImagePlus,Loader2,Paperclip,Plus,Trash2,X } from "lucide-react";
import { useRouter } from "next/navigation";
import { createBoardColumnAction,deleteBoardColumnAction } from "@/app/actions/columns";
import { createPostAction } from "@/app/actions/posts";
import { ModernPostCard } from "@/components/board/modern-post-card";
import { uploadBoardFile } from "@/lib/storage/upload-board-file";
import type { Board,BoardColumn,Group,Post,UserProfile } from "@/types/database";

type Draft={columnId:string;title:string;content:string;fileUrl:string|null;fileName:string|null;fileType:string|null;mediaPosition:"top"|"bottom"};
const blank=(columnId:string):Draft=>({columnId,title:"",content:"",fileUrl:null,fileName:null,fileType:null,mediaPosition:"bottom"});

export function ColumnBoard({board,group,profile,columns,initialPosts}:{board:Board;group:Group;profile:UserProfile;columns:BoardColumn[];initialPosts:Post[]}){
  const router=useRouter(),[posts,setPosts]=useState(initialPosts),[draft,setDraft]=useState<Draft|null>(null),[columnTitle,setColumnTitle]=useState(""),[addingColumn,setAddingColumn]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(""),[pending,startTransition]=useTransition(),teacher=profile.role==="teacher";
  function addColumn(){if(!columnTitle.trim()){setError("기둥 제목을 입력해 주세요.");return}startTransition(async()=>{const result=await createBoardColumnAction({boardId:board.id,title:columnTitle});if(!result.ok){setError(result.message||"기둥 생성 실패");return}setColumnTitle("");setAddingColumn(false);router.refresh()})}
  function removeColumn(id:string){if(!confirm("기둥을 삭제할까요? 글은 미분류 상태로 남습니다."))return;startTransition(async()=>{await deleteBoardColumnAction({boardId:board.id,columnId:id});router.refresh()})}
  async function attach(file?:File){if(!file||!draft)return;setUploading(true);setError("");const result=await uploadBoardFile({file,groupId:group.id,boardId:board.id,userId:profile.id});setUploading(false);if("error" in result){setError(result.error??"파일 업로드에 실패했습니다.");return}setDraft({...draft,fileUrl:result.publicUrl,fileName:result.name,fileType:result.type})}
  function savePost(){if(!draft)return;if(!draft.title.trim()){setError("글 제목은 반드시 입력해 주세요.");return}startTransition(async()=>{const visual=draft.fileType?.startsWith("image/")||draft.fileType?.startsWith("video/");const result=await createPostAction({boardId:board.id,columnId:draft.columnId,title:draft.title,content:draft.content,attachmentUrl:draft.fileUrl,attachmentName:draft.fileName,attachmentType:draft.fileType,mediaType:visual?(draft.fileType?.startsWith("video/")?"video":"image"):null,mediaPosition:draft.mediaPosition,color:["#FFF3B0","#DDF4E7","#E7E2FF","#FFE2E8"][posts.length%4]});if(!result.ok||!result.post){setError(result.message||"등록 실패");return}setPosts(current=>board.sort_order==="newest"?[result.post!,...current]:[...current,result.post!]);setDraft(null)})}
  return <div className={`column-board background-${board.background}`}><div className="column-board-head"><div><h2>{board.title}</h2><p>{board.description}</p></div>{teacher?<button className="column-add-main" onClick={()=>setAddingColumn(true)}><Plus/>기둥 만들기</button>:null}</div>{error?<p className="column-error">{error}</p>:null}<div className="column-track">{columns.map(column=><section className="board-column" key={column.id}><header><h3>{column.title}</h3>{teacher?<button onClick={()=>removeColumn(column.id)} aria-label="기둥 삭제"><Trash2/></button>:null}</header><button className="column-post-add" disabled={board.is_locked&&!teacher} onClick={()=>setDraft(blank(column.id))}><Plus/><span>{board.is_locked&&!teacher?"글쓰기가 잠겼어요":"이 기둥에 글 붙이기"}</span></button><div className="column-posts">{posts.filter(post=>post.column_id===column.id).map(post=><ModernPostCard key={post.id} post={post}/>)}</div></section>)}{teacher?<button className="empty-column-card" onClick={()=>setAddingColumn(true)}><Plus/><span>새 기둥</span></button>:null}</div>
    {!columns.length?<div className="column-empty"><h3>아직 기둥이 없어요</h3><p>선생님이 기둥을 만들면 학생 글을 차곡차곡 모을 수 있어요.</p>{teacher?<button className="primary-button" onClick={()=>setAddingColumn(true)}><Plus/>첫 기둥 만들기</button>:null}</div>:null}
    {addingColumn?<div className="column-modal-backdrop" onClick={()=>setAddingColumn(false)}><div className="column-dialog small" onClick={event=>event.stopPropagation()}><button className="modal-x" onClick={()=>setAddingColumn(false)}><X/></button><h2>새 기둥 만들기</h2><label>기둥 제목<input value={columnTitle} onChange={event=>setColumnTitle(event.target.value)} autoFocus maxLength={80} placeholder="예: 찬성 의견, 궁금한 점" onKeyDown={event=>{if(event.key==="Enter")addColumn()}}/></label><button className="primary-button" disabled={pending} onClick={addColumn}>{pending?<Loader2 className="animate-spin"/>:<Plus/>}기둥 만들기</button></div></div>:null}
    {draft?<div className="column-modal-backdrop" onClick={()=>setDraft(null)}><div className="column-dialog" onClick={event=>event.stopPropagation()}><button className="modal-x" onClick={()=>setDraft(null)}><X/></button><span className="dialog-kicker">{columns.find(column=>column.id===draft.columnId)?.title}</span><h2>새 포스트잇 붙이기</h2><label>글 제목 <b>필수</b><input value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})} required maxLength={100} placeholder="글의 제목을 입력하세요"/></label><label>내용<textarea value={draft.content} onChange={event=>setDraft({...draft,content:event.target.value})} rows={7} placeholder="친구들에게 전하고 싶은 생각을 적어 주세요"/></label><label className="file-picker"><input type="file" accept="image/*,video/*,.pdf,.hwp,.hwpx" onChange={event=>void attach(event.target.files?.[0])}/>{uploading?<Loader2 className="animate-spin"/>:<ImagePlus/>}<span>{draft.fileName||"사진, 동영상, PDF, 한글 파일 선택 (20MB 이하)"}</span></label>
      {draft.fileUrl?<fieldset className="column-media-position"><legend>첨부 매체 배치</legend><div>{([['top','글 위에 배치'],['bottom','글 아래에 배치']] as const).map(([value,label])=><label key={value} className={draft.mediaPosition===value?"active":""}><input type="radio" name="columnMediaPosition" checked={draft.mediaPosition===value} onChange={()=>setDraft({...draft,mediaPosition:value})}/>{label}</label>)}</div></fieldset>:null}
      <button className="primary-button post-submit" disabled={pending||uploading} onClick={savePost}>{pending?<Loader2 className="animate-spin"/>:<Paperclip/>}포스트잇 등록</button></div></div>:null}
  </div>
}
