"use client";
import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {ArrowLeft,CalendarDays,CheckCircle2,ClipboardCheck,Clock3,Eye,FileImage,Link2,Paperclip,Plus,Save,Send,ShieldCheck,Upload,X} from "lucide-react";import type {Assignment,AssignmentAttachment,AssignmentStudent,AssignmentSubmission,SubmissionStatus} from "@/types/assignments";import {TaskEditor} from "@/components/assignments/TaskEditor";
const assignmentKey="moduboard:assignments",submissionKey="moduboard:assignment-submissions";
const demo:Assignment={id:"welcome-assignment",title:"우리 동네 자랑거리 소개하기",description:"우리 동네에서 친구들에게 소개하고 싶은 장소나 자랑거리를 찾아보세요.\n사진이나 동영상을 넣고, 왜 소개하고 싶은지 자세히 적어 주세요.",attachments:[],dueDate:new Date(Date.now()+7*86400000).toISOString(),createdAt:new Date().toISOString(),createdBy:"teacher"};
function read<T>(key:string,fallback:T):T{if(typeof window==="undefined")return fallback;try{return JSON.parse(localStorage.getItem(key)??"") as T}catch{return fallback}}
function save(assignments:Assignment[],submissions:AssignmentSubmission[]){localStorage.setItem(assignmentKey,JSON.stringify(assignments));localStorage.setItem(submissionKey,JSON.stringify(submissions));window.dispatchEvent(new Event("assignment-change"))}
function fileData(file:File){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(file)})}

export function AssignmentCenter({role,user,students,assignmentId}:{role:"teacher"|"student";user:{id:string;name:string};students:AssignmentStudent[];assignmentId?:string}){
 const [assignments,setAssignments]=useState<Assignment[]>([demo]),[submissions,setSubmissions]=useState<AssignmentSubmission[]>([]),[create,setCreate]=useState(false),[review,setReview]=useState<AssignmentSubmission|null>(null),[ready,setReady]=useState(false);
 useEffect(()=>{const load=()=>{setAssignments(read(assignmentKey,[demo]));setSubmissions(read(submissionKey,[]));setReady(true)};load();addEventListener("storage",load);addEventListener("assignment-change",load);return()=>{removeEventListener("storage",load);removeEventListener("assignment-change",load)}},[]);
 function persist(nextA=assignments,nextS=submissions){setAssignments(nextA);setSubmissions(nextS);save(nextA,nextS)}
 if(!ready)return <div className="assignment-loading">과제방을 불러오고 있어요…</div>;
 if(assignmentId){const assignment=assignments.find(item=>item.id===assignmentId);return assignment?<AssignmentDetail assignment={assignment} role={role} user={user} students={students} submissions={submissions} persist={persist} review={review} setReview={setReview}/>:<div className="assignment-empty"><h2>과제를 찾을 수 없어요.</h2><Link href="/assignments">과제 목록으로</Link></div>}
 return <div className="assignment-page"><header className="assignment-hero"><div><p><ClipboardCheck/>CLASS ASSIGNMENTS</p><h1>모두의 과제방</h1><span>과제를 확인하고, 차근차근 작성하고, 선생님의 따뜻한 피드백을 받아요.</span></div>{role==="teacher"?<button className="bounce-hover" onClick={()=>setCreate(true)}><Plus/>새 과제 출제</button>:<div className="assignment-hero-icon">📝</div>}</header><div className="assignment-list-heading"><div><h2>우리 반 과제</h2><p>마감일과 제출 상태를 확인하세요.</p></div><span>{assignments.length}개</span></div><section className="assignment-grid">{assignments.map(item=>{const submitted=submissions.filter(value=>value.assignmentId===item.id&&value.status!=="draft").length,total=Math.max(students.length,role==="student"?1:0),mine=submissions.find(value=>value.assignmentId===item.id&&value.studentId===user.id);return <Link className="assignment-card bounce-hover" href={`/assignments/${item.id}`} key={item.id}><div className="assignment-card-top"><span className={new Date(item.dueDate)<new Date()?"closed":"open"}>{new Date(item.dueDate)<new Date()?"마감":"진행 중"}</span><ClipboardCheck/></div><h3>{item.title}</h3><p>{item.description}</p><div className="assignment-deadline"><CalendarDays/><span><small>마감일</small><b>{new Date(item.dueDate).toLocaleString("ko-KR",{month:"long",day:"numeric",hour:"2-digit",minute:"2-digit"})}</b></span></div><footer>{role==="teacher"?<><span>학급 제출률</span><b>{submitted}/{total}명</b></>:<><span>나의 상태</span><Status status={mine?.status??null}/></>}</footer></Link>})}</section>{create?<CreateModal userId={user.id} onClose={()=>setCreate(false)} onSave={item=>{persist([item,...assignments]);setCreate(false)}}/>:null}</div>
}

function AssignmentDetail({assignment,role,user,students,submissions,persist,review,setReview}:{assignment:Assignment;role:"teacher"|"student";user:{id:string;name:string};students:AssignmentStudent[];submissions:AssignmentSubmission[];persist:(a?:Assignment[],s?:AssignmentSubmission[])=>void;review:AssignmentSubmission|null;setReview:(value:AssignmentSubmission|null)=>void}){const mine=submissions.find(item=>item.assignmentId===assignment.id&&item.studentId===user.id),[content,setContent]=useState(mine?.content??""),[links,setLinks]=useState<string[]>(mine?.links??[]),[link,setLink]=useState(""),[media,setMedia]=useState(mine?.mediaUrls??[]),[notice,setNotice]=useState("");async function addMedia(files:FileList|null){if(!files)return;const next:AssignmentSubmission["mediaUrls"]=[];for(const file of Array.from(files).slice(0,5)){if(!file.type.startsWith("image/")&&!file.type.startsWith("video/"))continue;next.push({id:crypto.randomUUID(),type:(file.type.startsWith("video/")?"video":"image") as "video"|"image",url:await fileData(file),name:file.name})}setMedia(current=>[...current,...next])}function store(status:SubmissionStatus){const now=new Date().toISOString(),item:AssignmentSubmission={id:mine?.id??crypto.randomUUID(),assignmentId:assignment.id,studentId:user.id,studentName:user.name,content,mediaUrls:media,links,status,teacherFeedback:mine?.teacherFeedback??"",updatedAt:now,submittedAt:status==="submitted"?now:mine?.submittedAt};persist(undefined,[...submissions.filter(value=>value.id!==item.id),item]);setNotice(status==="draft"?"임시 저장했어요.":"과제를 제출했어요!")}
 return <div className="assignment-page detail"><Link className="assignment-back" href="/assignments"><ArrowLeft/>과제 목록</Link><section className="assignment-description"><div className="assignment-title-line"><span>ASSIGNMENT</span><Status status={mine?.status??null}/></div><h1>{assignment.title}</h1><div className="assignment-due"><CalendarDays/>마감 {new Date(assignment.dueDate).toLocaleString("ko-KR")}</div><p>{assignment.description}</p><Media attachments={assignment.attachments}/></section>
 {role==="student"?<section className="student-submission"><header><div><h2>나의 과제 작성</h2><p>임시 저장한 뒤 나중에 이어서 쓸 수 있어요.</p></div>{mine?.status==="reviewed"?<span className="review-stamp"><CheckCircle2/>검사 완료</span>:null}</header><label>과제 내용<TaskEditor value={content} onChange={setContent}/></label><div className="submission-tools"><label><Upload/>사진·동영상 첨부<input type="file" accept="image/*,video/*" multiple onChange={event=>addMedia(event.target.files)}/></label><div><input value={link} onChange={event=>setLink(event.target.value)} placeholder="https:// 링크 주소"/><button onClick={()=>{if(/^https?:\/\//.test(link)){setLinks(current=>[...current,link]);setLink("")}}}><Link2/>링크 추가</button></div></div><Media attachments={[...media.map(item=>({...item})),...links.map(url=>({id:url,type:"link" as const,url,name:url}))]} onRemove={id=>{setMedia(current=>current.filter(item=>item.id!==id));setLinks(current=>current.filter(url=>url!==id))}}/><footer><span>{notice}</span><button className="draft" onClick={()=>store("draft")}><Save/>임시 저장</button><button className="submit" onClick={()=>store("submitted")} disabled={!content.replace(/<[^>]*>/g,"").trim()}><Send/>과제 제출하기</button></footer>{mine?.status==="reviewed"?<div className="teacher-feedback"><ShieldCheck/><div><b>선생님 피드백</b><p>{mine.teacherFeedback||"참 잘했어요!"}</p></div></div>:null}</section>:<TeacherChecklist students={students} submissions={submissions.filter(item=>item.assignmentId===assignment.id)} onReview={setReview}/>} {review?<ReviewModal submission={review} onClose={()=>setReview(null)} onSave={feedback=>{persist(undefined,submissions.map(item=>item.id===review.id?{...item,status:"reviewed",teacherFeedback:feedback,updatedAt:new Date().toISOString()}:item));setReview(null)}}/>:null}</div>}

function TeacherChecklist({students,submissions,onReview}:{students:AssignmentStudent[];submissions:AssignmentSubmission[];onReview:(item:AssignmentSubmission)=>void}){return <section className="assignment-checklist"><header><div><h2>학생 제출 체크리스트</h2><p>작성 중인 내용도 바로 확인하고 피드백할 수 있습니다.</p></div><span>{submissions.filter(item=>item.status!=="draft").length}/{students.length}명 제출</span></header><div>{students.map(student=>{const item=submissions.find(value=>value.studentId===student.id);return <article className={item?.status??"missing"} key={student.id}><div><span>{student.studentNum??"-"}</span><b>{student.name}</b></div><Status status={item?.status??null}/><small>{item?new Date(item.updatedAt).toLocaleString("ko-KR"):"아직 작성 기록 없음"}</small><button disabled={!item} onClick={()=>item&&onReview(item)}><Eye/>과제/작성 화면 바로보기</button></article>})}</div></section>}
function Status({status}:{status:SubmissionStatus|null}){return <span className={`assignment-status ${status??"missing"}`}>{status==="draft"?"작성 중…":status==="submitted"?"제출 완료":status==="reviewed"?"검사 완료":"미제출"}</span>}
function Media({attachments,onRemove}:{attachments:AssignmentAttachment[];onRemove?:(id:string)=>void}){return attachments.length?<div className="assignment-media">{attachments.map(item=><figure key={item.id}>{item.type==="image"?<img src={item.url} alt={item.name}/>:item.type==="video"?<video src={item.url} controls/>:<a href={item.url} target="_blank" rel="noreferrer"><Link2/><span>{item.name}</span></a>}{onRemove?<button onClick={()=>onRemove(item.id)}><X/></button>:null}</figure>)}</div>:null}
function CreateModal({userId,onClose,onSave}:{userId:string;onClose:()=>void;onSave:(item:Assignment)=>void}){const [attachments,setAttachments]=useState<AssignmentAttachment[]>([]),[link,setLink]=useState("");async function files(list:FileList|null){if(!list)return;const next:AssignmentAttachment[]=[];for(const file of Array.from(list).slice(0,5))if(file.type.startsWith("image/")||file.type.startsWith("video/"))next.push({id:crypto.randomUUID(),type:file.type.startsWith("video/")?"video":"image",url:await fileData(file),name:file.name});setAttachments(current=>[...current,...next])}function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget),title=String(data.get("title")??"").trim(),description=String(data.get("description")??"").trim(),dueDate=String(data.get("dueDate")??"");if(!title||!description||!dueDate)return;onSave({id:crypto.randomUUID(),title,description,attachments,dueDate:new Date(dueDate).toISOString(),createdAt:new Date().toISOString(),createdBy:userId})}return <div className="assignment-modal-backdrop" onClick={onClose}><form className="assignment-modal create" onClick={event=>event.stopPropagation()} onSubmit={submit}><button type="button" className="modal-x" onClick={onClose}><X/></button><small>NEW ASSIGNMENT</small><h2>새 과제 출제</h2><label>과제 제목<input name="title" required placeholder="과제 제목을 입력하세요"/></label><label>과제 안내<textarea name="description" required rows={8} placeholder="준비물, 활동 방법, 주의사항을 자세히 적어 주세요."/></label><label>마감 일시<input name="dueDate" type="datetime-local" required/></label><div className="assignment-create-tools"><label><FileImage/>사진·동영상 첨부<input type="file" accept="image/*,video/*" multiple onChange={event=>files(event.target.files)}/></label><div><input value={link} onChange={event=>setLink(event.target.value)} placeholder="외부 자료 링크"/><button type="button" onClick={()=>{if(/^https?:\/\//.test(link)){setAttachments(current=>[...current,{id:crypto.randomUUID(),type:"link",url:link,name:link}]);setLink("")}}}><Plus/>추가</button></div></div><Media attachments={attachments} onRemove={id=>setAttachments(current=>current.filter(item=>item.id!==id))}/><button className="assignment-primary"><ClipboardCheck/>과제 출제하기</button></form></div>}
function ReviewModal({submission,onClose,onSave}:{submission:AssignmentSubmission;onClose:()=>void;onSave:(feedback:string)=>void}){const [feedback,setFeedback]=useState(submission.teacherFeedback);return <div className="assignment-modal-backdrop" onClick={onClose}><div className="assignment-modal review" onClick={event=>event.stopPropagation()}><button className="modal-x" onClick={onClose}><X/></button><small>TEACHER REVIEW</small><h2>{submission.studentName} 학생 과제</h2><div className="review-content"><RichAssignmentContent html={submission.content}/><Media attachments={[...submission.mediaUrls,...submission.links.map(url=>({id:url,type:"link" as const,url,name:url}))]}/></div><label>선생님 피드백<textarea rows={6} value={feedback} onChange={event=>setFeedback(event.target.value)} placeholder="잘한 점과 다음에 보완할 점을 따뜻하게 적어 주세요."/></label><button className="assignment-primary" onClick={()=>onSave(feedback.trim())}><CheckCircle2/>피드백 저장 및 검사 완료</button></div></div>}

function RichAssignmentContent({html}:{html:string}){return html?<div className="assignment-rich-readonly" dangerouslySetInnerHTML={{__html:html}}/>:<p>작성 내용이 없습니다.</p>}
