"use client";
import { useEffect, useMemo, useState } from "react";
import { Bot, Check, Crown, Eye, FileUp, Flag, Link2, Lock, MessageCircle, Plus, Send, Shield, Sparkles } from "lucide-react";
import { PhaseStepper } from "@/components/phase-stepper";
import { usePhasedActivity } from "@/hooks/use-phased-activity";
import { evaluateDebateWithAI } from "@/lib/ai/evaluate-debate";
import type { ActivityStudent, DebateComment, DebatePost, DebateTopic, Phase, Team } from "@/types/activities";

const phases: Phase[] = [
  { key: "team", label: "입장 정하기", description: "찬성·반대 선택", durationMinutes: 15 },
  { key: "strategy", label: "입론 준비", description: "팀 비공개 자료실", durationMinutes: 60 },
  { key: "debate", label: "토론하기", description: "순차 공개·반론", durationMinutes: 60 },
  { key: "decision", label: "승리 팀 판정", description: "교사 또는 AI 판정", durationMinutes: 1440 },
];
const teamLabel = (team: Team) => team === "pro" ? "찬성팀" : "반대팀";

export function DebateModule({ currentUser, role, students, initialCanCreateTopic = false }: { currentUser: ActivityStudent; role: "teacher" | "student"; students: ActivityStudent[]; initialCanCreateTopic?: boolean }) {
  const engine = usePhasedActivity(phases); const [canCreateTopic, setCanCreateTopic] = useState(initialCanCreateTopic); const [teams, setTeams] = useState<Record<string, Team>>({}); const [posts, setPosts] = useState<DebatePost[]>([]); const [leaders, setLeaders] = useState<Partial<Record<Team, string>>>({}); const [claim, setClaim] = useState(""); const [evidence, setEvidence] = useState(""); const [media, setMedia] = useState(""); const [revealCount, setRevealCount] = useState(1); const [decisionMode, setDecisionMode] = useState<"teacher" | "ai">("ai"); const [winner, setWinner] = useState<Team>(); const [evaluation, setEvaluation] = useState(""); const [evaluating, setEvaluating] = useState(false);
  const myTeam = teams[currentUser.id]; const allStudents = students.length ? students : [currentUser];
  const topic: DebateTopic = { id: "debate-main", title: "교내 휴대폰 사용을 허용해야 할까요?", phases, currentPhase: engine.phaseIndex, phaseEndsAt: new Date(engine.endsAt).toISOString(), teams, posts, leaders, decisionMode, winner, evaluation };
  useEffect(() => { if (engine.phaseIndex !== 2) return; const timer = window.setInterval(() => setRevealCount((n) => Math.min(posts.length, n + 1)), 8000); return () => window.clearInterval(timer); }, [engine.phaseIndex, posts.length]);
  function chooseTeam(team: Team) { setTeams((t) => ({ ...t, [currentUser.id]: team })); }
  function advance() { if (engine.phaseIndex === 0) { const next = { ...teams }; let pro = Object.values(next).filter((t) => t === "pro").length; let con = Object.values(next).filter((t) => t === "con").length; for (const student of allStudents) if (!next[student.id]) { const team: Team = pro < con ? "pro" : con < pro ? "con" : Math.random() < .5 ? "pro" : "con"; next[student.id] = team; team === "pro" ? pro++ : con++; } setTeams(next); } engine.advance(); }
  function addPost() { if (!myTeam || !claim.trim() || !evidence.trim()) return; setPosts((p) => [...p, { id: crypto.randomUUID(), authorId: currentUser.id, authorName: currentUser.name, team: myTeam, claim: claim.trim(), evidence: evidence.trim(), mediaUrl: media || undefined, comments: [], order: p.filter((x) => x.team === myTeam).length }]); setClaim(""); setEvidence(""); setMedia(""); }
  function comment(postId: string, type: DebateComment["type"], content: string) {
    if (!content.trim()) return;
    setPosts((all) => all.map((post) => {
      if (post.id !== postId) return post;
      if (engine.phaseIndex === 2 && post.authorId === currentUser.id) {
        const target = [...post.comments].reverse().find((item) => item.type === "question" && !item.answer);
        if (!target) return post;
        return { ...post, comments: post.comments.map((item) => item.id === target.id ? { ...item, answer: content.trim() } : item) };
      }
      return { ...post, comments: [...post.comments, { id: crypto.randomUUID(), authorId: currentUser.id, authorName: currentUser.name, type, content: content.trim() }] };
    }));
  }
  async function aiDecision() { setEvaluating(true); const result = await evaluateDebateWithAI(topic.title, posts); setWinner(result.winner); setEvaluation(result.summary); setEvaluating(false); }
  return <div className="phased-page debate-module"><header className="phased-hero debate"><div><p>논리로 성장하는 우리 반</p><h1>모두의 토론</h1><span>{topic.title}</span></div><Sparkles /></header><PhaseStepper phases={phases} current={engine.phaseIndex} secondsLeft={engine.secondsLeft} role={role} onAdvance={advance} onDuration={engine.setDuration} />
    {role === "teacher" ? <div className="topic-permission"><span><b>학생 주제 개설 권한</b><small>canCreateTopic: {canCreateTopic ? "허용" : "허용 안 함"}</small></span><label className="vote-switch"><input type="checkbox" checked={canCreateTopic} onChange={(e) => setCanCreateTopic(e.target.checked)} /><span /></label></div> : null}
    {engine.phaseIndex === 0 ? <TeamPhase students={allStudents} teams={teams} currentUser={currentUser} role={role} chooseTeam={chooseTeam} /> : null}
    {engine.phaseIndex === 1 ? <StrategyPhase role={role} myTeam={myTeam} posts={posts} teams={teams} students={allStudents} leaders={leaders} setLeaders={setLeaders} claim={claim} setClaim={setClaim} evidence={evidence} setEvidence={setEvidence} media={media} setMedia={setMedia} addPost={addPost} comment={comment} /> : null}
    {engine.phaseIndex === 2 ? <MainDebate posts={posts} revealCount={role === "teacher" ? posts.length : revealCount} currentUser={currentUser} comment={comment} /> : null}
    {engine.phaseIndex === 3 ? <DecisionPhase role={role} mode={decisionMode} setMode={setDecisionMode} winner={winner} setWinner={setWinner} evaluation={evaluation} evaluating={evaluating} onAI={aiDecision} /> : null}
  </div>;
}

function TeamPhase({ students, teams, currentUser, role, chooseTeam }: { students: ActivityStudent[]; teams: Record<string, Team>; currentUser: ActivityStudent; role: "teacher" | "student"; chooseTeam: (t: Team) => void }) { return <section className="phase-panel"><div className="phase-intro"><span>1단계</span><h2>나는 어느 입장인가요?</h2><p>기한 안에 선택하지 않으면 인원이 적은 팀으로 공정하게 자동 배정돼요.</p></div>{role === "student" ? <div className="debate-team-pick"><button className={teams[currentUser.id] === "pro" ? "active pro" : "pro"} onClick={() => chooseTeam("pro")}><Shield /><b>찬성</b><span>허용해야 해요</span></button><button className={teams[currentUser.id] === "con" ? "active con" : "con"} onClick={() => chooseTeam("con")}><Flag /><b>반대</b><span>허용하면 안 돼요</span></button></div> : null}<div className="team-rosters">{(["pro", "con"] as Team[]).map((team) => <div className={team} key={team}><h3>{teamLabel(team)} <span>{students.filter((s) => teams[s.id] === team).length}명</span></h3>{students.filter((s) => teams[s.id] === team).map((s) => <p key={s.id}><i>{s.name.slice(0, 1)}</i>{s.studentNum ? `${s.studentNum}번 ` : ""}{s.name}</p>)}</div>)}</div></section>; }

function StrategyPhase({ role, myTeam, posts, teams, students, leaders, setLeaders, claim, setClaim, evidence, setEvidence, media, setMedia, addPost, comment }: { role: "teacher" | "student"; myTeam?: Team; posts: DebatePost[]; teams: Record<string, Team>; students: ActivityStudent[]; leaders: Partial<Record<Team, string>>; setLeaders: React.Dispatch<React.SetStateAction<Partial<Record<Team, string>>>>; claim: string; setClaim: (v: string) => void; evidence: string; setEvidence: (v: string) => void; media: string; setMedia: (v: string) => void; addPost: () => void; comment: (id: string, type: DebateComment["type"], text: string) => void }) { const visibleTeams: Team[] = role === "teacher" ? ["pro", "con"] : myTeam ? [myTeam] : []; return <section className="phase-panel"><div className="private-banner"><Lock /><div><b>팀 전용 비공개 준비실</b><span>{role === "teacher" ? "슈퍼바이저 권한으로 양 팀을 모두 보고 있어요." : "상대 팀에게는 이 자료와 댓글이 보이지 않아요."}</span></div></div>{myTeam ? <div className="strategy-compose"><h3>{teamLabel(myTeam)} 주장 자료 등록</h3><input value={claim} onChange={(e) => setClaim(e.target.value)} placeholder="핵심 주장을 적어 주세요" /><textarea value={evidence} onChange={(e) => setEvidence(e.target.value)} placeholder="주장의 근거와 사례를 적어 주세요" /><label><Link2 /><input value={media} onChange={(e) => setMedia(e.target.value)} placeholder="사진·동영상·링크 주소" /></label><button onClick={addPost}><Plus />팀 자료 등록</button></div> : null}<div className="strategy-columns">{visibleTeams.map((team) => <div key={team}><header><h3>{teamLabel(team)} 자료실</h3><select value={leaders[team] ?? ""} onChange={(e) => setLeaders((l) => ({ ...l, [team]: e.target.value }))}><option value="">팀 리더 투표/선출</option>{students.filter((s) => teams[s.id] === team).map((s) => <option value={s.id} key={s.id}>{s.name}</option>)}</select></header>{posts.filter((p) => p.team === team).map((p, index) => <ArgumentCard key={p.id} post={p} badge={`발표 ${index + 1}순서`} commentType="team" onComment={comment} />)}</div>)}</div></section>; }

function MainDebate({ posts, revealCount, currentUser, comment }: { posts: DebatePost[]; revealCount: number; currentUser: ActivityStudent; comment: (id: string, type: DebateComment["type"], text: string) => void }) { const ordered = useMemo(() => [...posts].sort((a, b) => a.order - b.order), [posts]); return <section className="phase-panel"><div className="phase-intro"><span>3단계</span><h2>주장 글이 순서대로 공개되고 있어요</h2><p>상대 팀은 반론이나 질문을 남길 수 있고, 글쓴이는 질문에만 답변할 수 있습니다.</p></div><div className="public-arguments">{ordered.map((post, i) => i < revealCount ? <ArgumentCard key={post.id} post={post} badge={`${i + 1}번째 공개`} commentType="question" onComment={comment} currentUser={currentUser} /> : <div className="locked-argument" key={post.id}><Lock /><b>다음 공개를 기다려 주세요</b><span>교사가 설정한 간격에 맞춰 열립니다.</span></div>)}</div></section>; }

function ArgumentCard({ post, badge, commentType, onComment, currentUser }: { post: DebatePost; badge: string; commentType: DebateComment["type"]; onComment: (id: string, type: DebateComment["type"], text: string) => void; currentUser?: ActivityStudent }) { const [text, setText] = useState(""); const [type, setType] = useState<"question" | "rebuttal">("question"); return <article className={`argument-card ${post.team}`}><header><span>{post.authorName}</span><b>{teamLabel(post.team)}</b><em>{badge}</em></header><h3>{post.claim}</h3><p>{post.evidence}</p>{post.mediaUrl ? <a href={post.mediaUrl} target="_blank" rel="noreferrer"><FileUp />첨부 자료 열기</a> : null}<div className="argument-comments">{post.comments.map((c) => <div key={c.id}><b>{c.type === "question" ? "질문" : c.type === "rebuttal" ? "반론" : "팀 댓글"} · {c.authorName}</b><p>{c.content}</p>{c.answer ? <small>답변: {c.answer}</small> : null}</div>)}</div><div className="comment-compose">{commentType !== "team" && currentUser?.id !== post.authorId ? <select value={type} onChange={(e) => setType(e.target.value as "question" | "rebuttal")}><option value="question">질문</option><option value="rebuttal">반론</option></select> : null}<input value={text} onChange={(e) => setText(e.target.value)} placeholder={currentUser?.id === post.authorId ? "질문에 답변할 수 있어요" : "댓글을 남겨 주세요"} /><button onClick={() => { onComment(post.id, commentType === "team" ? "team" : type, text); setText(""); }}><Send /></button></div></article>; }

function DecisionPhase({ role, mode, setMode, winner, setWinner, evaluation, evaluating, onAI }: { role: "teacher" | "student"; mode: "teacher" | "ai"; setMode: (m: "teacher" | "ai") => void; winner?: Team; setWinner: (t: Team) => void; evaluation: string; evaluating: boolean; onAI: () => void }) { return <section className="phase-panel decision-panel"><div className="phase-intro"><span>4단계</span><h2>승리 팀 판정</h2><p>근거의 적절성과 질문·답변의 논리성을 종합해 판정합니다.</p></div>{role === "teacher" ? <><div className="decision-mode"><button className={mode === "teacher" ? "active" : ""} onClick={() => setMode("teacher")}><Crown />교사 직접 판정</button><button className={mode === "ai" ? "active" : ""} onClick={() => setMode("ai")}><Bot />AI 판정</button></div>{mode === "teacher" ? <div className="winner-buttons"><button onClick={() => setWinner("pro")}>찬성팀 승리</button><button onClick={() => setWinner("con")}>반대팀 승리</button></div> : <button className="ai-evaluate" disabled={evaluating} onClick={onAI}><Bot />{evaluating ? "AI가 토론을 분석하고 있어요…" : "AI 판정 시작하기"}</button>}</> : null}{winner ? <div className={`winner-result ${winner}`}><Crown /><h2>{teamLabel(winner)} 승리!</h2><p>{evaluation || "선생님의 종합 판정으로 승리 팀이 결정되었습니다."}</p></div> : <div className="decision-wait"><Eye />판정 결과를 기다리고 있어요.</div>}</section>; }

