"use client";
import { useEffect, useMemo, useState } from "react";
import { Crown, Eye, Flag, Lock, Send, Shield, Sparkles, Users } from "lucide-react";
import { PhaseStepper } from "@/components/phase-stepper";
import { AudienceVoteResults } from "@/components/audience-vote-results";
import { TeacherDebateJudge } from "@/components/teacher-debate-judge";
import { DiscussionPostEditor } from "@/components/discussion-post-editor";
import { RichPostContent } from "@/components/rich-post-content";
import { usePhasedActivity } from "@/hooks/use-phased-activity";
import { recordPointActivity } from "@/lib/my-room/points";
import type { ActivityStudent, DebateComment, DebateDecision, DebatePost, DebateTopic, DebateUserRole, DiscussionContentBlock, Phase, Team } from "@/types/activities";

const phases: Phase[] = [
  { key: "team", label: "입장 정하기", description: "찬성·반대 선택", durationMinutes: 15 },
  { key: "strategy", label: "입론 준비", description: "팀 비공개 자료실", durationMinutes: 60 },
  { key: "debate", label: "토론하기", description: "순차 공개·반론", durationMinutes: 60 },
  { key: "decision", label: "승리 팀 판정", description: "교사·청중 판정", durationMinutes: 1440 },
];
const teamLabel = (team: Team) => team === "pro" ? "찬성팀" : "반대팀";

export function DebateModule({ currentUser, role, students, groupId, initialCanCreateTopic = false }: { currentUser: ActivityStudent; role: "teacher" | "student"; students: ActivityStudent[]; groupId: string; initialCanCreateTopic?: boolean }) {
  const engine = usePhasedActivity(phases); const [canCreateTopic, setCanCreateTopic] = useState(initialCanCreateTopic); const [maxTeamSize, setMaxTeamSize] = useState(4); const [teams, setTeams] = useState<Record<string, DebateUserRole>>({}); const [posts, setPosts] = useState<DebatePost[]>([]); const [leaders, setLeaders] = useState<Partial<Record<Team, string>>>({}); const [revealCount, setRevealCount] = useState(1); const [decisionMode, setDecisionMode] = useState<"teacher" | "audience">("audience"); const [winner, setWinner] = useState<DebateDecision>(); const [teacherFeedback, setTeacherFeedback] = useState(""); const [audienceVotes, setAudienceVotes] = useState<Record<string, Team>>({}); const [audienceVoteClosed, setAudienceVoteClosed] = useState(false); const [allowUnassignedAudienceVote, setAllowUnassignedAudienceVote] = useState(true);
  const myRole = teams[currentUser.id]; const myTeam: Team | undefined = myRole === "pro" || myRole === "con" ? myRole : undefined; const allStudents = students.length ? students : [currentUser];
  const topic: DebateTopic = { id: "debate-main", title: "교내 휴대폰 사용을 허용해야 할까요?", phases, currentPhase: engine.phaseIndex, phaseEndsAt: new Date(engine.endsAt).toISOString(), maxTeamSize, userRoles: teams, posts, leaders, decisionMode, audienceVotes, audienceVoteClosed, allowUnassignedAudienceVote, winner, teacherFeedback };
  useEffect(() => { if (engine.phaseIndex !== 2) return; const timer = window.setInterval(() => setRevealCount((n) => Math.min(posts.length, n + 1)), 8000); return () => window.clearInterval(timer); }, [engine.phaseIndex, posts.length]);
  function chooseTeam(nextRole: DebateUserRole) { setTeams((current) => { const next = { ...current }; const count = (team: Team) => Object.entries(next).filter(([id, value]) => id !== currentUser.id && value === team).length; const bothFull = count("pro") >= maxTeamSize && count("con") >= maxTeamSize; next[currentUser.id] = bothFull || ((nextRole === "pro" || nextRole === "con") && count(nextRole) >= maxTeamSize) ? "audience" : nextRole; return next; }); }
  function assignUnselected(current: Record<string, DebateUserRole>) { const next = { ...current }; let pro = Object.values(next).filter((team) => team === "pro").length; let con = Object.values(next).filter((team) => team === "con").length; for (const student of allStudents) if (!next[student.id]) { if (pro >= maxTeamSize && con >= maxTeamSize) next[student.id] = "audience"; else if (pro >= maxTeamSize) { next[student.id] = "con"; con++; } else if (con >= maxTeamSize) { next[student.id] = "pro"; pro++; } else { const team: Team = pro < con ? "pro" : con < pro ? "con" : Math.random() < .5 ? "pro" : "con"; next[student.id] = team; team === "pro" ? pro++ : con++; } } return next; }
  function advance() { if (engine.phaseIndex === 0) setTeams((current) => assignUnselected(current)); engine.advance(); }
  useEffect(() => { if (engine.phaseIndex === 1) setTeams((current) => assignUnselected(current)); }, [engine.phaseIndex]);
  function addPost(claim: string, contentBlocks: DiscussionContentBlock[]) { if (!myTeam) return; const id=crypto.randomUUID(); const evidence = contentBlocks.filter((block) => block.type === "text").map((block) => block.content).filter(Boolean).join("\n\n"); setPosts((p) => [...p, { id, authorId: currentUser.id, authorName: currentUser.name, team: myTeam, claim, evidence, contentBlocks, comments: [], order: p.filter((x) => x.team === myTeam).length }]); recordPointActivity(currentUser.id,"debatePost",id); }
  function comment(postId: string, type: DebateComment["type"], content: string) {
    if (!content.trim() || myRole === "audience") return;
    setPosts((all) => all.map((post) => {
      if (post.id !== postId) return post;
      if (engine.phaseIndex === 2 && post.authorId === currentUser.id) {
        const target = [...post.comments].reverse().find((item) => item.type === "question" && !item.answer);
        if (!target) return post;
        return { ...post, comments: post.comments.map((item) => item.id === target.id ? { ...item, answer: content.trim() } : item) };
      }
      const commentId=crypto.randomUUID(); recordPointActivity(currentUser.id,"comment",commentId); return { ...post, comments: [...post.comments, { id: commentId, authorId: currentUser.id, authorName: currentUser.name, type, content: content.trim() }] };
    }));
  }
  function closeAudienceVote() { const values = Object.values(audienceVotes); const pro = values.filter((v) => v === "pro").length; const con = values.length - pro; setWinner(pro === con ? "draw" : pro > con ? "pro" : "con"); setAudienceVoteClosed(true); }
  return <div className="phased-page debate-module"><header className="phased-hero debate"><div><p>논리로 성장하는 우리 반</p><h1>모두의 토론</h1><span>{topic.title}</span></div><Sparkles /></header><PhaseStepper phases={phases} current={engine.phaseIndex} secondsLeft={engine.secondsLeft} role={role} onAdvance={advance} onDuration={engine.setDuration} />
    {role === "teacher" ? <div className="topic-permission"><span><b>학생 주제 개설 권한</b><small>canCreateTopic: {canCreateTopic ? "허용" : "허용 안 함"}</small></span><label className="vote-switch"><input type="checkbox" checked={canCreateTopic} onChange={(e) => setCanCreateTopic(e.target.checked)} /><span /></label></div> : null}
    {engine.phaseIndex === 0 ? <TeamPhase students={allStudents} teams={teams} currentUser={currentUser} role={role} maxTeamSize={maxTeamSize} setMaxTeamSize={setMaxTeamSize} chooseTeam={chooseTeam} /> : null}
    {engine.phaseIndex === 1 ? <StrategyPhase role={role} myRole={myRole} myTeam={myTeam} posts={posts} teams={teams} students={allStudents} leaders={leaders} setLeaders={setLeaders} groupId={groupId} userId={currentUser.id} addPost={addPost} comment={comment} /> : null}
    {engine.phaseIndex === 2 ? <MainDebate posts={posts} revealCount={role === "teacher" ? posts.length : revealCount} currentUser={currentUser} canInteract={role === "student" && (myRole === "pro" || myRole === "con")} comment={comment} /> : null}
    {engine.phaseIndex === 3 ? <DecisionPhase role={role} userRole={myRole} myVote={audienceVotes[currentUser.id]} mode={decisionMode} setMode={setDecisionMode} votes={audienceVotes} voteClosed={audienceVoteClosed} winner={winner} feedback={teacherFeedback} allowUnassigned={allowUnassignedAudienceVote} setAllowUnassigned={setAllowUnassignedAudienceVote} onVote={(team) => setAudienceVotes((v) => ({ ...v, [currentUser.id]: team }))} onCloseVote={closeAudienceVote} onTeacherJudge={(result, feedback) => { setWinner(result); setTeacherFeedback(feedback); }} /> : null}
  </div>;
}

function TeamPhase({ students, teams, currentUser, role, maxTeamSize, setMaxTeamSize, chooseTeam }: { students: ActivityStudent[]; teams: Record<string, DebateUserRole>; currentUser: ActivityStudent; role: "teacher" | "student"; maxTeamSize: number; setMaxTeamSize: (n: number) => void; chooseTeam: (t: DebateUserRole) => void }) { const proCount = students.filter((s) => teams[s.id] === "pro").length; const conCount = students.filter((s) => teams[s.id] === "con").length; const bothFull = proCount >= maxTeamSize && conCount >= maxTeamSize; return <section className="phase-panel"><div className="phase-intro row"><div><span>1단계</span><h2>나는 어느 입장인가요?</h2><p>빈자리가 없으면 청중 판정단이 되어 토론을 관람하고 마지막에 투표해요.</p></div>{role === "teacher" ? <label className="team-size-setting">팀당 최대 인원 <input type="number" min="1" max="20" value={maxTeamSize} onChange={(e) => setMaxTeamSize(Math.max(1, Number(e.target.value)))} />명</label> : null}</div>{role === "student" ? <div className={`debate-team-pick ${bothFull ? "full" : ""}`}><button disabled={proCount >= maxTeamSize && teams[currentUser.id] !== "pro"} className={teams[currentUser.id] === "pro" ? "active pro" : "pro"} onClick={() => chooseTeam("pro")}><Shield /><b>{proCount >= maxTeamSize ? "찬성 마감" : "찬성"}</b><span>{proCount}/{maxTeamSize}명</span></button><button disabled={conCount >= maxTeamSize && teams[currentUser.id] !== "con"} className={teams[currentUser.id] === "con" ? "active con" : "con"} onClick={() => chooseTeam("con")}><Flag /><b>{conCount >= maxTeamSize ? "반대 마감" : "반대"}</b><span>{conCount}/{maxTeamSize}명</span></button><button className={teams[currentUser.id] === "audience" ? "active audience" : "audience"} onClick={() => chooseTeam("audience")}><Users /><b>청중으로 참여하기</b><span>{bothFull ? "양 팀 정원이 모두 찼어요" : "토론을 보고 승리 팀을 판정해요"}</span></button></div> : null}<div className="team-rosters three">{(["pro", "con", "audience"] as DebateUserRole[]).map((team) => <div className={team} key={team}><h3>{team === "audience" ? "청중 판정단" : teamLabel(team)} <span>{students.filter((s) => teams[s.id] === team).length}명{team !== "audience" ? ` / ${maxTeamSize}명` : ""}</span></h3>{students.filter((s) => teams[s.id] === team).map((s) => <p key={s.id}><i>{s.name.slice(0, 1)}</i>{s.studentNum ? `${s.studentNum}번 ` : ""}{s.name}</p>)}</div>)}</div></section>; }

function StrategyPhase({ role, myRole, myTeam, posts, teams, students, leaders, setLeaders, groupId, userId, addPost, comment }: { role: "teacher" | "student"; myRole?: DebateUserRole; myTeam?: Team; posts: DebatePost[]; teams: Record<string, DebateUserRole>; students: ActivityStudent[]; leaders: Partial<Record<Team, string>>; setLeaders: React.Dispatch<React.SetStateAction<Partial<Record<Team, string>>>>; groupId: string; userId: string; addPost: (claim: string, blocks: DiscussionContentBlock[]) => void; comment: (id: string, type: DebateComment["type"], text: string) => void }) { const visibleTeams: Team[] = role === "teacher" || myRole === "audience" ? ["pro", "con"] : myTeam ? [myTeam] : []; return <section className="phase-panel"><div className="private-banner">{myRole === "audience" ? <Eye /> : <Lock />}<div><b>{myRole === "audience" ? "청중 관람 모드" : "팀 전용 비공개 준비실"}</b><span>{role === "teacher" ? "슈퍼바이저 권한으로 양 팀을 모두 보고 있어요." : myRole === "audience" ? "자료를 읽을 수 있지만 글이나 댓글은 작성할 수 없어요." : "상대 팀에게는 이 자료와 댓글이 보이지 않아요."}</span></div></div>{myTeam ? <DiscussionPostEditor groupId={groupId} userId={userId} onSubmit={addPost} heading={`${teamLabel(myTeam)} 입장 글 작성`} helper="근거 글 사이에 사진과 동영상을 넣고 URL을 그대로 적어 링크로 만들 수 있어요." titlePlaceholder="핵심 주장을 한 문장으로 적어 주세요" bodyPlaceholder="주장의 근거와 사례를 자세히 적어 주세요. URL은 자동으로 클릭 가능한 링크가 됩니다." submitLabel="팀 주장 등록하기" storageFolder="debate-assets" /> : null}<div className="strategy-columns">{visibleTeams.map((team) => <div key={team}><header><h3>{teamLabel(team)} 자료실</h3>{myRole !== "audience" ? <select value={leaders[team] ?? ""} onChange={(e) => setLeaders((l) => ({ ...l, [team]: e.target.value }))}><option value="">팀 리더 투표/선출</option>{students.filter((s) => teams[s.id] === team).map((s) => <option value={s.id} key={s.id}>{s.name}</option>)}</select> : null}</header>{posts.filter((p) => p.team === team).map((p, index) => <ArgumentCard key={p.id} post={p} badge={`발표 ${index + 1}순서`} commentType="team" onComment={comment} readOnly={myRole === "audience"} />)}</div>)}</div></section>; }

function MainDebate({ posts, revealCount, currentUser, canInteract, comment }: { posts: DebatePost[]; revealCount: number; currentUser: ActivityStudent; canInteract: boolean; comment: (id: string, type: DebateComment["type"], text: string) => void }) { const ordered = useMemo(() => [...posts].sort((a, b) => a.order - b.order), [posts]); return <section className="phase-panel"><div className="phase-intro"><span>3단계</span><h2>주장 글이 순서대로 공개되고 있어요</h2><p>{canInteract ? "상대 팀은 반론이나 질문을 남기고, 글쓴이는 질문에 답변할 수 있어요." : "청중 판정단은 토론 과정을 관람하며 마지막 판정을 준비해요."}</p></div><div className="public-arguments">{ordered.map((post, i) => i < revealCount ? <ArgumentCard key={post.id} post={post} badge={`${i + 1}번째 공개`} commentType="question" onComment={comment} currentUser={currentUser} readOnly={!canInteract} /> : <div className="locked-argument" key={post.id}><Lock /><b>다음 공개를 기다려 주세요</b><span>교사가 설정한 간격에 맞춰 열립니다.</span></div>)}</div></section>; }

function ArgumentCard({ post, badge, commentType, onComment, currentUser, readOnly = false }: { post: DebatePost; badge: string; commentType: DebateComment["type"]; onComment: (id: string, type: DebateComment["type"], text: string) => void; currentUser?: ActivityStudent; readOnly?: boolean }) { const [text, setText] = useState(""); const [type, setType] = useState<"question" | "rebuttal">("question"); return <article className={`argument-card ${post.team}`}><header><span>{post.authorName}</span><b>{teamLabel(post.team)}</b><em>{badge}</em></header><h3>{post.claim}</h3><RichPostContent blocks={post.contentBlocks} fallback={post.evidence} /><div className="argument-comments">{post.comments.map((c) => <div key={c.id}><b>{c.type === "question" ? "질문" : c.type === "rebuttal" ? "반론" : "팀 댓글"} · {c.authorName}</b><p>{c.content}</p>{c.answer ? <small>답변: {c.answer}</small> : null}</div>)}</div>{!readOnly ? <div className="comment-compose">{commentType !== "team" && currentUser?.id !== post.authorId ? <select value={type} onChange={(e) => setType(e.target.value as "question" | "rebuttal")}><option value="question">질문</option><option value="rebuttal">반론</option></select> : null}<input value={text} onChange={(e) => setText(e.target.value)} placeholder={currentUser?.id === post.authorId ? "질문에 답변할 수 있어요" : "댓글을 남겨 주세요"} /><button onClick={() => { onComment(post.id, commentType === "team" ? "team" : type, text); setText(""); }}><Send /></button></div> : <div className="read-only-badge"><Eye />청중 읽기 전용</div>}</article>; }

function DecisionPhase({ role, userRole, myVote, mode, setMode, votes, voteClosed, winner, feedback, allowUnassigned, setAllowUnassigned, onVote, onCloseVote, onTeacherJudge }: { role: "teacher" | "student"; userRole?: DebateUserRole; myVote?: Team; mode: "teacher" | "audience"; setMode: (m: "teacher" | "audience") => void; votes: Record<string, Team>; voteClosed: boolean; winner?: DebateDecision; feedback: string; allowUnassigned: boolean; setAllowUnassigned: (v: boolean) => void; onVote: (team: Team) => void; onCloseVote: () => void; onTeacherJudge: (winner: DebateDecision, feedback: string) => void }) { const canVote = role === "student" && (userRole === "audience" || (allowUnassigned && !userRole)); return <section className="phase-panel decision-panel"><div className="phase-intro"><span>4단계</span><h2>승리 팀 결정</h2><p>청중 판정단의 투표 또는 선생님의 직접 판정으로 결과를 정해요.</p></div>{role === "teacher" ? <><div className="decision-mode"><button className={mode === "teacher" ? "active" : ""} onClick={() => setMode("teacher")}><Crown />교사 직접 판정</button><button className={mode === "audience" ? "active" : ""} onClick={() => setMode("audience")}><Users />청중 투표 판정</button></div>{mode === "audience" ? <label className="unassigned-vote-option"><span><b>미배정 학생도 투표 허용</b><small>토론자로 참여하지 않은 학생에게 판정권을 줍니다.</small></span><span className="vote-switch"><input type="checkbox" checked={allowUnassigned} onChange={(e) => setAllowUnassigned(e.target.checked)} /><i /></span></label> : null}</> : null}{mode === "audience" ? <AudienceVoteResults canVote={canVote} myVote={myVote} votes={votes} closed={voteClosed} role={role} winner={winner} onVote={onVote} onClose={onCloseVote} /> : role === "teacher" ? <TeacherDebateJudge publishedWinner={winner} publishedFeedback={feedback} onPublish={onTeacherJudge} /> : winner ? <div className={`winner-result ${winner}`}><Crown /><h2>{winner === "draw" ? "무승부" : `${teamLabel(winner)} 승리!`}</h2><p>{feedback}</p></div> : <div className="decision-wait"><Eye />선생님의 판정 결과를 기다리고 있어요.</div>}</section>; }

