"use client";
import { useMemo, useState } from "react";
import { Check, Combine, Crown, FileUp, Link2, MessageSquareText, Pencil, Plus, Sparkles, ThumbsUp, Trophy } from "lucide-react";
import { PhaseStepper } from "@/components/phase-stepper";
import { usePhasedActivity } from "@/hooks/use-phased-activity";
import type { ActivityStudent, DiscussionIdea, DiscussionTopic, Phase } from "@/types/activities";

const phases: Phase[] = [
  { key: "ideas", label: "의견 모으기", description: "자유로운 아이디어", durationMinutes: 60 },
  { key: "shortlist", label: "1차 투표", description: "대표 의견 선정", durationMinutes: 60 },
  { key: "refine", label: "다듬고 합치기", description: "어필·병합·수정", durationMinutes: 60 },
  { key: "final", label: "최종 투표", description: "학급 결정 가결", durationMinutes: 1440 },
];

export function DiscussionModule({ currentUser, role, initialCanCreateTopic = false }: { currentUser: ActivityStudent; role: "teacher" | "student"; initialCanCreateTopic?: boolean }) {
  const engine = usePhasedActivity(phases); const [canCreateTopic, setCanCreateTopic] = useState(initialCanCreateTopic); const [topN, setTopN] = useState(3); const [ideas, setIdeas] = useState<DiscussionIdea[]>([]); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [media, setMedia] = useState(""); const [shortlisted, setShortlisted] = useState<string[]>([]); const [finalVotes, setFinalVotes] = useState<Record<string, string>>({}); const [winner, setWinner] = useState<string>();
  const topic: DiscussionTopic = { id: "discussion-main", title: "우리 학교 쉼터를 어떻게 바꾸면 좋을까요?", phases, currentPhase: engine.phaseIndex, phaseEndsAt: new Date(engine.endsAt).toISOString(), shortlistCount: topN, ideas, shortlistedIds: shortlisted, finalVotes, winnerId: winner };
  function addIdea() { if (!title.trim() || !content.trim()) return; setIdeas((all) => [{ id: crypto.randomUUID(), authorId: currentUser.id, authorName: currentUser.name, title: title.trim(), content: content.trim(), mediaUrl: media || undefined, votes: [] }, ...all]); setTitle(""); setContent(""); setMedia(""); }
  function voteIdea(id: string) { setIdeas((all) => all.map((idea) => ({ ...idea, votes: idea.id === id ? Array.from(new Set([...idea.votes, currentUser.id])) : idea.votes.filter((v) => v !== currentUser.id) }))); }
  function advance() { if (engine.phaseIndex === 1) setShortlisted([...ideas].sort((a, b) => b.votes.length - a.votes.length).slice(0, topN).map((i) => i.id)); if (engine.phaseIndex === 2 && !shortlisted.length) setShortlisted(ideas.slice(0, topN).map((i) => i.id)); if (engine.phaseIndex === 3) { const counts = shortlisted.map((id) => ({ id, count: Object.values(finalVotes).filter((v) => v === id).length })).sort((a, b) => b.count - a.count); setWinner(counts[0]?.id); } engine.advance(); }
  function merge(sourceId: string, targetId: string) { if (!targetId || sourceId === targetId) return; const source = ideas.find((i) => i.id === sourceId), target = ideas.find((i) => i.id === targetId); if (!source || !target) return; setIdeas((all) => all.filter((i) => i.id !== sourceId).map((i) => i.id === targetId ? { ...i, title: `${i.title} + ${source.title}`, content: `${i.content}\n\n${source.content}`, mergedFrom: [...(i.mergedFrom ?? []), source.id] } : i)); setShortlisted((ids) => ids.filter((id) => id !== sourceId)); }
  const finalIdeas = ideas.filter((i) => shortlisted.includes(i.id));
  return <div className="phased-page discussion-module"><header className="phased-hero discussion"><div><p>함께 생각하고 함께 결정해요</p><h1>모두의 토의</h1><span>{topic.title}</span></div><MessageSquareText /></header><PhaseStepper phases={phases} current={engine.phaseIndex} secondsLeft={engine.secondsLeft} role={role} onAdvance={advance} onDuration={engine.setDuration} />
    {role === "teacher" ? <div className="topic-permission"><span><b>학생 주제 개설 권한</b><small>canCreateTopic: {canCreateTopic ? "허용" : "허용 안 함"}</small></span><label className="vote-switch"><input type="checkbox" checked={canCreateTopic} onChange={(e) => setCanCreateTopic(e.target.checked)} /><span /></label></div> : null}
    {engine.phaseIndex === 0 ? <section className="phase-panel"><div className="phase-intro"><span>1단계</span><h2>떠오르는 생각을 자유롭게 올려요</h2><p>사진·동영상·링크를 함께 올려도 좋아요. 아이디어는 많을수록 좋아요!</p></div><div className="idea-compose"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="의견 제목" /><textarea value={content} onChange={(e) => setContent(e.target.value)} placeholder="왜 좋은 생각인지 설명해 주세요" /><label><Link2 /><input value={media} onChange={(e) => setMedia(e.target.value)} placeholder="관련 사진·영상·링크" /></label><button onClick={addIdea}><Plus />의견 제출</button></div><IdeaGrid ideas={ideas} /></section> : null}
    {engine.phaseIndex === 1 ? <section className="phase-panel"><div className="phase-intro row"><div><span>2단계</span><h2>대표 의견을 뽑아요</h2><p>마음에 드는 의견 하나에 투표해 주세요.</p></div>{role === "teacher" ? <label className="top-n">대표 의견 수<select value={topN} onChange={(e) => setTopN(Number(e.target.value))}><option value="3">상위 3개</option><option value="4">상위 4개</option><option value="5">상위 5개</option></select></label> : null}</div><div className="shortlist-grid">{ideas.map((idea) => <article key={idea.id} className={idea.votes.includes(currentUser.id) ? "voted" : ""}><span>{idea.authorName}</span><h3>{idea.title}</h3><p>{idea.content}</p><button onClick={() => voteIdea(idea.id)}><ThumbsUp />{idea.votes.includes(currentUser.id) ? "선택했어요" : "이 의견에 투표"}<b>{idea.votes.length}</b></button></article>)}</div></section> : null}
    {engine.phaseIndex === 2 ? <section className="phase-panel"><div className="phase-intro"><span>3단계</span><h2>대표 의견을 더 멋지게 다듬어요</h2><p>작성자는 내용을 수정하고, 비슷한 의견끼리 하나로 합칠 수 있어요.</p></div><div className="refine-grid">{finalIdeas.map((idea) => <RefineCard key={idea.id} idea={idea} all={finalIdeas} canEdit={role === "teacher" || idea.authorId === currentUser.id} onUpdate={(patch) => setIdeas((all) => all.map((i) => i.id === idea.id ? { ...i, ...patch } : i))} onMerge={(target) => merge(idea.id, target)} />)}</div></section> : null}
    {engine.phaseIndex === 3 ? <section className="phase-panel"><div className="phase-intro"><span>4단계</span><h2>우리 반의 최종 결정을 선택해요</h2><p>가장 많은 표를 받은 의견 하나가 최종 결정으로 선정됩니다.</p></div><div className="final-vote-grid">{finalIdeas.map((idea) => { const count = Object.values(finalVotes).filter((id) => id === idea.id).length; const selected = finalVotes[currentUser.id] === idea.id; return <button className={selected ? "selected" : ""} key={idea.id} onClick={() => setFinalVotes((v) => ({ ...v, [currentUser.id]: idea.id }))}><span>{selected ? <Check /> : <Sparkles />}</span><div><b>{idea.title}</b><p>{idea.content}</p></div><em>{count}표</em></button>; })}</div>{winner ? <div className="discussion-winner"><Trophy /><span><b>우리 반 최종 결정</b><h2>{ideas.find((i) => i.id === winner)?.title}</h2></span></div> : null}</section> : null}
  </div>;
}

function IdeaGrid({ ideas }: { ideas: DiscussionIdea[] }) { return ideas.length ? <div className="idea-grid">{ideas.map((idea) => <article key={idea.id}><span>{idea.authorName}</span><h3>{idea.title}</h3><p>{idea.content}</p>{idea.mediaUrl ? <a href={idea.mediaUrl} target="_blank" rel="noreferrer"><FileUp />관련 자료</a> : null}</article>)}</div> : <div className="phase-empty">첫 번째 의견을 기다리고 있어요.</div>; }
function RefineCard({ idea, all, canEdit, onUpdate, onMerge }: { idea: DiscussionIdea; all: DiscussionIdea[]; canEdit: boolean; onUpdate: (p: Partial<DiscussionIdea>) => void; onMerge: (id: string) => void }) { const [editing, setEditing] = useState(false); const [title, setTitle] = useState(idea.title); const [content, setContent] = useState(idea.content); return <article className="refine-card"><header><Crown /><span><b>{idea.authorName}의 대표 의견</b><small>{idea.votes.length}표로 선정</small></span>{canEdit ? <button onClick={() => setEditing(!editing)}><Pencil /></button> : null}</header>{editing ? <><input value={title} onChange={(e) => setTitle(e.target.value)} /><textarea value={content} onChange={(e) => setContent(e.target.value)} /><button className="save-refine" onClick={() => { onUpdate({ title, content }); setEditing(false); }}>수정 저장</button></> : <><h3>{idea.title}</h3><p>{idea.content}</p></>} {canEdit && all.length > 1 ? <label className="merge-control"><Combine />다른 의견과 합치기<select defaultValue="" onChange={(e) => onMerge(e.target.value)}><option value="">의견 선택</option>{all.filter((i) => i.id !== idea.id).map((i) => <option value={i.id} key={i.id}>{i.title}</option>)}</select></label> : null}</article>; }
