"use client";
import { useState } from "react";
import { ImagePlus, Loader2, Plus, Send, Trash2, Video } from "lucide-react";
import { uploadBoardFile } from "@/lib/storage/upload-board-file";
import type { DiscussionContentBlock } from "@/types/activities";

const textBlock = (): DiscussionContentBlock => ({ id: crypto.randomUUID(), type: "text", content: "" });
type Props = { groupId: string; userId: string; onSubmit: (title: string, blocks: DiscussionContentBlock[]) => void; heading?: string; helper?: string; titlePlaceholder?: string; bodyPlaceholder?: string; submitLabel?: string; storageFolder?: string };

export function DiscussionPostEditor({ groupId, userId, onSubmit, heading = "새 의견 작성", helper = "본문 중간 원하는 곳에 사진과 동영상을 넣을 수 있어요.", titlePlaceholder = "의견의 제목을 입력하세요", bodyPlaceholder = "내 생각과 그 이유를 자세히 적어 보세요. URL을 입력하면 게시 후 클릭 가능한 링크가 됩니다.", submitLabel = "의견 게시하기", storageFolder = "discussion-assets" }: Props) {
  const [title, setTitle] = useState(""); const [blocks, setBlocks] = useState<DiscussionContentBlock[]>([textBlock()]); const [uploading, setUploading] = useState<string>(); const [error, setError] = useState("");
  function updateText(id: string, content: string) { setBlocks((all) => all.map((block) => block.id === id ? { ...block, content } : block)); }
  function addText(afterId: string) { setBlocks((all) => { const index = all.findIndex((block) => block.id === afterId); const next = [...all]; next.splice(index + 1, 0, textBlock()); return next; }); }
  async function attach(afterId: string, file?: File) { if (!file) return; if (!file.type.startsWith("image/") && !file.type.startsWith("video/")) { setError("사진 또는 동영상 파일만 첨부할 수 있어요."); return; } setUploading(afterId); setError(""); const result = await uploadBoardFile({ file, groupId, boardId: storageFolder, userId }); setUploading(undefined); if ("error" in result) { setError(result.error ?? "업로드에 실패했습니다."); return; } const media: DiscussionContentBlock = { id: crypto.randomUUID(), type: file.type.startsWith("video/") ? "video" : "image", url: result.publicUrl, fileName: result.name }; setBlocks((all) => { const index = all.findIndex((block) => block.id === afterId); const next = [...all]; next.splice(index + 1, 0, media, textBlock()); return next; }); }
  function remove(id: string) { setBlocks((all) => { const next = all.filter((block) => block.id !== id); return next.length ? next : [textBlock()]; }); }
  function submit() { const clean = blocks.filter((block) => block.type !== "text" || block.content?.trim()); if (!title.trim() || !clean.some((block) => block.type === "text" && block.content?.trim())) { setError("제목과 본문 내용을 입력해 주세요."); return; } onSubmit(title.trim(), clean); setTitle(""); setBlocks([textBlock()]); setError(""); }
  return <div className="discussion-editor"><div className="discussion-editor-top"><span>{heading}</span><small>{helper}</small></div><input className="discussion-title-input" value={title} onChange={(event) => setTitle(event.target.value)} placeholder={titlePlaceholder} maxLength={100} /><div className="discussion-blocks">{blocks.map((block, index) => block.type === "text" ? <div className="discussion-text-block" key={block.id}><textarea value={block.content ?? ""} onChange={(event) => updateText(block.id, event.target.value)} rows={index === 0 ? 5 : 3} placeholder={index === 0 ? bodyPlaceholder : "사진이나 영상에 대한 설명을 이어서 적어 보세요."} /><div className="discussion-insert-bar"><span>이 아래에 넣기</span><label><ImagePlus /><b>사진</b><input type="file" accept="image/*" onChange={(event) => void attach(block.id, event.target.files?.[0])} /></label><label><Video /><b>동영상</b><input type="file" accept="video/*" onChange={(event) => void attach(block.id, event.target.files?.[0])} /></label><button onClick={() => addText(block.id)}><Plus />글 단락</button>{blocks.length > 1 ? <button className="remove" onClick={() => remove(block.id)}><Trash2 /></button> : null}{uploading === block.id ? <Loader2 className="animate-spin upload-spinner" /> : null}</div></div> : <div className={`discussion-media-block ${block.type}`} key={block.id}>{block.type === "image" ? <img src={block.url} alt={block.fileName ?? "첨부 이미지"} /> : <video src={block.url} controls preload="metadata" />}<div><span>{block.fileName}</span><button onClick={() => remove(block.id)}><Trash2 />삭제</button></div></div>)}</div>{error ? <p className="discussion-editor-error">{error}</p> : null}<button className="discussion-submit" disabled={!!uploading} onClick={submit}><Send />{submitLabel}</button></div>;
}
