"use client";
import {useEffect,useMemo,useState} from "react";
import {ArrowLeft,Coins,Gift,Home,Lock,MessageCircle,Pencil,Send,ShieldCheck,ShoppingBag,Sparkles,Trash2,Users} from "lucide-react";
import {canViewGuestbook} from "@/lib/my-room/permissions";
import {awardActivityPoints} from "@/lib/my-room/points";
import type {GuestbookEntry,MyRoomConfig,MyRoomUser,RoomStoreItem} from "@/types/my-room";
import type {TongStudent} from "@/types/tong";

const items:RoomStoreItem[]=[
 {id:"bg-cozy",name:"포근한 보랏빛 방",type:"background",price:0,emoji:"🏡",color:"#e8dcff"},{id:"bg-space",name:"반짝 우주 정거장",type:"background",price:180,emoji:"🚀",color:"#cbd8ff"},
 {id:"char-bunny",name:"토끼 탐험가",type:"character",price:0,emoji:"🐰",color:"#ffe2ee"},{id:"char-robot",name:"꼬마 로봇",type:"character",price:130,emoji:"🤖",color:"#dcecff"},
 {id:"bed-cloud",name:"구름 침대",type:"bed",price:100,emoji:"🛏️",color:"#e4f4ff"},{id:"desk-star",name:"별빛 책상",type:"desk",price:90,emoji:"🪑",color:"#fff0ca"},{id:"wall-plant",name:"행복 화분",type:"wall",price:60,emoji:"🌿",color:"#dff3df"},{id:"door-rainbow",name:"무지개 간판",type:"doorTheme",price:75,emoji:"🌈",color:"#ffe1ee"}
];
const starter=["bg-cozy","char-bunny","bed-cloud","desk-star","wall-plant","door-rainbow"];
const base=(name:string):MyRoomConfig=>({backgroundId:"bg-cozy",characterId:"char-bunny",placedItems:{bed:"bed-cloud",desk:"desk-star",wall:"wall-plant"},doorTitle:`${name}의 반짝이는 방`,doorTheme:"door-rainbow"});

export function MyRoomCenter({profile,students,pointName="포인트"}:{profile:MyRoomUser;students:TongStudent[];pointName?:string}){
 const directory=students.length?students:[{id:profile.id,name:profile.name,studentNum:null}];
 const [view,setView]=useState<"directory"|"room"|"store">("directory"),[targetId,setTargetId]=useState(profile.id),[points,setPoints]=useState(profile.points),[inventory,setInventory]=useState<string[]>(starter),[config,setConfig]=useState(base(profile.name)),[editing,setEditing]=useState(false),[entries,setEntries]=useState<GuestbookEntry[]>([]),[secret,setSecret]=useState(false),[message,setMessage]=useState("");
 const target=directory.find(student=>student.id===targetId)??directory[0],mine=target?.id===profile.id;
 const room=useMemo(()=>mine?config:friendRoom(target?.name??"친구",directory.findIndex(student=>student.id===target?.id)),[config,directory,mine,target]);
 useEffect(()=>{const key=`moduboard:myroom:${profile.id}`,saved=localStorage.getItem(key),shared=Number(localStorage.getItem(`moduboard:points:${profile.id}`)??0);if(saved)try{const data=JSON.parse(saved);setPoints(Math.max(data.points,shared,profile.points));setInventory(data.inventory);setConfig(data.config);setEntries(data.entries??[])}catch{}else{const day=new Date().toISOString().slice(0,10),attendance=`moduboard:attendance:${profile.id}:${day}`;setPoints(Math.max(shared,profile.points));if(!localStorage.getItem(attendance)){setPoints(value=>awardActivityPoints(value,"attendance"));localStorage.setItem(attendance,"1")}}},[profile.id,profile.points]);
 useEffect(()=>{localStorage.setItem(`moduboard:myroom:${profile.id}`,JSON.stringify({points,inventory,config,entries}));localStorage.setItem(`moduboard:points:${profile.id}`,String(points))},[config,entries,inventory,points,profile.id]);
 const visible=entries.filter(entry=>entry.targetUserId===target?.id&&canViewGuestbook({...profile,points,inventory},entry));
 function visit(id:string){setTargetId(id);setView("room");setEditing(false)}
 function buy(item:RoomStoreItem){if(inventory.includes(item.id)||points<item.price)return;setPoints(value=>value-item.price);setInventory(current=>[...current,item.id])}
 function equip(item:RoomStoreItem){if(!mine||!inventory.includes(item.id))return;if(item.type==="background")setConfig(current=>({...current,backgroundId:item.id}));else if(item.type==="character")setConfig(current=>({...current,characterId:item.id}));else if(item.type==="doorTheme")setConfig(current=>({...current,doorTheme:item.id}));else setConfig(current=>({...current,placedItems:{...current.placedItems,[item.type]:item.id}}))}
 function write(){if(!message.trim()||!target)return;setEntries(current=>[{id:crypto.randomUUID(),targetUserId:target.id,authorId:profile.id,authorName:profile.name,content:message.trim(),isSecret:secret,createdAt:new Date().toISOString()},...current]);setMessage("");setSecret(false)}
 return <div className="myroom-page"><header className="myroom-hero"><div><p><Sparkles/>MY ROOM WORLD</p><h1>마이룸 & {pointName} 상점</h1><span>활동으로 받은 {pointName}을 모아 나만의 입체 방을 꾸며 보세요.</span></div><div className="point-wallet"><Coins/><span><small>나의 {pointName}</small><b>{points.toLocaleString()} {pointName}</b></span></div></header>
 <nav className="myroom-tabs"><button className={view==="directory"?"active":""} onClick={()=>setView("directory")}><Users/>친구들의 마이룸</button><button className={view==="room"&&mine?"active":""} onClick={()=>visit(profile.id)}><Home/>내 마이룸</button><button className={view==="store"?"active":""} onClick={()=>setView("store")}><ShoppingBag/>{pointName} 상점</button></nav>
 {view==="directory"?<section><Heading title="우리 반 마이룸" text="간판을 눌러 친구의 방에 놀러 가 보세요." side={`${directory.length}개의 방`}/><div className="room-directory">{directory.map((student,index)=><button key={student.id} className={`room-door theme-${index%4}`} onClick={()=>visit(student.id)}><div className="door-sky">{["☀️","🌙","⭐","🌈"][index%4]}</div><span className="door-avatar">{["🐰","🐻","🐱","🐶"][index%4]}</span><div><b>{student.id===profile.id?config.doorTitle:`${student.name}의 마이룸`}</b><small>{student.studentNum?`${student.studentNum}번 · `:""}문을 눌러 들어가요</small></div></button>)}</div></section>:null}
 {view==="room"&&target?<section className="room-detail"><div className="room-detail-bar"><button onClick={()=>setView("directory")}><ArrowLeft/>목록으로</button><div><h2>{room.doorTitle}</h2><span>{mine?"내 방":`${target.name} 친구의 방`}</span></div>{mine?<button className="edit-room" onClick={()=>setEditing(!editing)}><Pencil/>{editing?"꾸미기 완료":"내 마이룸 꾸미기"}</button>:null}</div>
 <div className={`isometric-room ${room.backgroundId}`}><img src="/myroom/isometric-room.png" alt="아이소메트릭 마이룸 배경"/><span className="room-character">{room.characterId==="char-robot"?"🤖":"🐰"}</span><span className="slot bed">{emoji(room.placedItems.bed)}</span><span className="slot desk">{emoji(room.placedItems.desk)}</span><span className="slot wall">{emoji(room.placedItems.wall)}</span></div>
 {editing?<div className="room-inventory"><h3><Gift/>보유 아이템</h3><div>{items.filter(item=>inventory.includes(item.id)).map(item=><button key={item.id} onClick={()=>equip(item)} style={{background:item.color}}><span>{item.emoji}</span><b>{item.name}</b><small>눌러서 장착</small></button>)}</div></div>:null}
 <div className="room-guestbook"><h3><MessageCircle/>방명록</h3>{profile.role==="teacher"?<p className="teacher-supervisor-note"><ShieldCheck/>교사 수퍼유저 모드: 비밀글을 포함한 모든 글을 확인하고 삭제할 수 있습니다.</p>:null}<div className="guestbook-compose"><textarea value={message} onChange={event=>setMessage(event.target.value)} placeholder="친구에게 따뜻한 인사를 남겨 보세요."/><label><input type="checkbox" checked={secret} onChange={event=>setSecret(event.target.checked)}/><Lock/>비밀글</label><button onClick={write}><Send/>남기기</button></div><div className="guestbook-list">{visible.length?visible.map(entry=><article key={entry.id}><span>{entry.authorName.slice(0,1)}</span><div><b>{entry.authorName}{entry.isSecret?<em><Lock/>비밀글</em>:null}</b><p>{entry.content}</p></div>{profile.role==="teacher"?<button onClick={()=>setEntries(current=>current.filter(item=>item.id!==entry.id))}><Trash2/>삭제</button>:null}</article>):<p>아직 방명록이 없어요. 첫 인사를 남겨 보세요!</p>}</div></div></section>:null}
 {view==="store"?<section><Heading title={`${pointName} 상점`} text={`활동으로 모은 ${pointName}으로 꾸미기 아이템을 구매하세요.`} side={`${points} ${pointName} 보유`}/><div className="room-store">{items.map(item=>{const owned=inventory.includes(item.id);return <article key={item.id} style={{background:item.color}}><span>{item.emoji}</span><small>{item.type}</small><h3>{item.name}</h3><button disabled={owned||points<item.price} onClick={()=>buy(item)}>{owned?<><ShieldCheck/>보유 중</>:<><Coins/>{item.price} {pointName}</>}</button></article>})}</div></section>:null}</div>
}
function friendRoom(name:string,index:number):MyRoomConfig{const variant=Math.max(0,index);return {...base(name),backgroundId:variant%2?"bg-space":"bg-cozy",characterId:variant%3?"char-bunny":"char-robot",doorTitle:`${name}의 마이룸`}}
function emoji(id?:string){return items.find(item=>item.id===id)?.emoji??"✨"}
function Heading({title,text,side}:{title:string;text:string;side:string}){return <div className="myroom-heading"><div><h2>{title}</h2><p>{text}</p></div><span>{side}</span></div>}
