"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarDays, Check, ChevronRight, Clock3, Edit3, Plus, Shuffle, Sparkles, Trash2, Trophy, X, Zap } from "lucide-react";
import { buildChemistryRanking, calculateMatchCount } from "@/lib/tong/calculate-match-count";
import { recordPointActivity } from "@/lib/my-room/points";
import type { DailyQuestion, TongOption, TongStudent, UserVote } from "@/types/tong";

const questionPool = [
  ["탕수육을 먹을 때 나는?", "부먹 🥣", "찍먹 🥢"],
  ["초능력을 가진다면?", "순간이동 ⚡", "시간여행 ⏰"],
  ["주말에 더 좋은 날씨는?", "눈 오는 날 ❄️", "비 오는 날 ☔"],
  ["학교가 끝난 뒤에는?", "친구와 운동하기 ⚽", "집에서 게임하기 🎮"],
  ["여행을 떠난다면?", "계획대로 착착 🗺️", "마음 가는 대로 🚲"],
  ["간식 하나만 고른다면?", "아이스크림 🍦", "감자칩 🥔"],
  ["하루 동안 동물이 된다면?", "하늘을 나는 새 🐦", "바다의 돌고래 🐬"],
] as const;

function hash(text: string) { let value = 0; for (const char of text) value = (value * 31 + char.charCodeAt(0)) >>> 0; return value; }
function fromPool(date: string, seed: string, source: DailyQuestion["source"]): DailyQuestion { const item = questionPool[hash(seed) % questionPool.length]; return { id: `tong-${source}-${seed}`, date, prompt: item[0], optionA: item[1], optionB: item[2], source, createdAt: new Date().toISOString() }; }
function dailyQuestion(date: string) { return fromPool(date, date, "daily"); }
function previousQuestion(date: string, offset: number) { const day = new Date(`${date}T12:00:00+09:00`); day.setDate(day.getDate() - offset); const key = day.toISOString().slice(0, 10); return dailyQuestion(key); }
function seedHistory(students: TongStudent[], today: string): UserVote[] { return Array.from({ length: 14 }, (_, index) => previousQuestion(today, index + 1)).flatMap((question) => students.map((student) => ({ userId: student.id, questionId: question.id, selectedOption: (hash(`${student.id}-${question.id}`) % 2 ? "A" : "B") as TongOption, votedAt: `${question.date}T09:00:00+09:00` }))); }

export function TongCenter({ currentUser, students, role, today, currentHour }: { currentUser: TongStudent; students: TongStudent[]; role: "teacher" | "student"; today: string; currentHour: number }) {
  const classmates = students.length ? students : [currentUser]; const questionStore = `moduboard:tong:questions:${today}`;
  const initialQuestions = currentHour >= 8 ? [dailyQuestion(today)] : [];
  const [questions, setQuestions] = useState<DailyQuestion[]>(initialQuestions); const [activeId, setActiveId] = useState(initialQuestions[0]?.id ?? ""); const [answers, setAnswers] = useState<Record<string, TongOption>>({});
  const [tab, setTab] = useState<"today" | "ranking">("today"); const [friend, setFriend] = useState<TongStudent>(); const [celebrate, setCelebrate] = useState(false); const [editor, setEditor] = useState<DailyQuestion | "new">();
  const active = questions.find((question) => question.id === activeId) ?? questions[0];

  useEffect(() => { const saved = window.localStorage.getItem(questionStore); if (saved) { try { const parsed = JSON.parse(saved) as DailyQuestion[]; const daily = dailyQuestion(today); const merged = currentHour >= 8 && !parsed.some((question) => question.source === "daily") ? [daily, ...parsed] : parsed; setQuestions(merged); setActiveId(merged[0]?.id ?? ""); if (merged.length !== parsed.length) window.localStorage.setItem(questionStore, JSON.stringify(merged)); } catch {} } }, [currentHour, questionStore, today]);
  useEffect(() => { const loaded: Record<string, TongOption> = {}; for (const question of questions) { const value = window.localStorage.getItem(`moduboard:tong:${currentUser.id}:${question.id}`); if (value === "A" || value === "B") loaded[question.id] = value; } setAnswers((current) => ({ ...current, ...loaded })); }, [currentUser.id, questions]);
  useEffect(() => { const now = new Date(); const next = new Date(now); if (currentHour < 8) next.setHours(8, 0, 0, 0); else { next.setDate(next.getDate() + 1); next.setHours(8, 0, 0, 0); } const timer = window.setTimeout(() => window.location.reload(), Math.max(1000, next.getTime() - now.getTime())); return () => window.clearTimeout(timer); }, [currentHour]);

  const historicalVotes = useMemo(() => seedHistory(classmates, today), [classmates, today]);
  const todayVotes = useMemo<UserVote[]>(() => questions.flatMap((question) => { const simulated = classmates.filter((student) => student.id !== currentUser.id).map<UserVote>((student) => ({ userId: student.id, questionId: question.id, selectedOption: (hash(`${student.id}-${question.id}`) % 2 ? "A" : "B") as TongOption, votedAt: `${today}T09:00:00+09:00` })); return answers[question.id] ? [...simulated, { userId: currentUser.id, questionId: question.id, selectedOption: answers[question.id], votedAt: new Date().toISOString() }] : simulated; }), [answers, classmates, currentUser.id, questions, today]);
  const allVotes = useMemo(() => [...historicalVotes, ...todayVotes], [historicalVotes, todayVotes]); const ranking = useMemo(() => buildChemistryRanking(currentUser.id, classmates, allVotes), [allVotes, classmates, currentUser.id]);
  const selected = active ? answers[active.id] : undefined; const activeVotes = active ? todayVotes.filter((vote) => vote.questionId === active.id) : []; const aCount = activeVotes.filter((vote) => vote.selectedOption === "A").length; const total = activeVotes.length; const aRate = total ? Math.round(aCount / total * 100) : 0; const bRate = total ? 100 - aRate : 0;
  const sameFriends = active && selected ? classmates.filter((student) => student.id !== currentUser.id && activeVotes.some((vote) => vote.userId === student.id && vote.selectedOption === selected)) : []; const match = friend ? calculateMatchCount(currentUser.id, friend.id, allVotes) : null;

  function persist(next: DailyQuestion[]) { setQuestions(next); setActiveId((id) => next.some((question) => question.id === id) ? id : next[0]?.id ?? ""); window.localStorage.setItem(questionStore, JSON.stringify(next)); }
  function addRandom() { const question = fromPool(today, `${Date.now()}-${questions.length}`, "random"); persist([...questions, question]); setActiveId(question.id); }
  function saveQuestion(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const prompt = String(form.get("prompt") ?? "").trim(); const optionA = String(form.get("optionA") ?? "").trim(); const optionB = String(form.get("optionB") ?? "").trim(); if (!prompt || !optionA || !optionB) return; if (editor === "new") { const question: DailyQuestion = { id: `tong-teacher-${crypto.randomUUID()}`, date: today, prompt, optionA, optionB, source: "teacher", createdAt: new Date().toISOString() }; persist([...questions, question]); setActiveId(question.id); } else if (editor) persist(questions.map((question) => question.id === editor.id ? { ...question, prompt, optionA, optionB } : question)); setEditor(undefined); }
  function removeQuestion(question: DailyQuestion) { if (!window.confirm("이 질문을 삭제할까요?")) return; persist(questions.filter((item) => item.id !== question.id)); }
  function vote(option: TongOption) { if (!active || selected || role !== "student") return; window.localStorage.setItem(`moduboard:tong:${currentUser.id}:${active.id}`, option); setAnswers((current) => ({ ...current, [active.id]: option })); recordPointActivity(currentUser.id,"vote",active.id); setCelebrate(true); window.setTimeout(() => setCelebrate(false), 1700); }

  return <div className="tong-center"><header className="tong-hero"><div><p><Sparkles /> DAILY CHEMISTRY</p><h1>모두의 통 ⚡</h1><span>매일 아침 8시, 친구들과 통하는 새로운 질문을 만나요!</span></div><div className="tong-streak"><b>기본 질문 오전 8시 공개</b><span><Clock3 /> 교사는 언제든 추가 가능</span></div></header>
    <nav className="tong-tabs"><button className={tab === "today" ? "active" : ""} onClick={() => setTab("today")}><Zap />오늘의 밸런스</button><button className={tab === "ranking" ? "active" : ""} onClick={() => setTab("ranking")}><Trophy />우리 반 케미 랭킹</button></nav>
    {tab === "today" ? <><div className="tong-question-toolbar"><div><b>오늘의 질문</b><span>{questions.length}개</span></div>{role === "teacher" ? <div><button onClick={addRandom}><Shuffle />추천 질문 자동 추가</button><button className="primary" onClick={() => setEditor("new")}><Plus />직접 만들기</button></div> : null}</div>
      {questions.length ? <div className="tong-question-chips">{questions.map((question, index) => <button className={question.id === active?.id ? "active" : ""} key={question.id} onClick={() => setActiveId(question.id)}><span>{question.source === "daily" ? "☀️" : question.source === "random" ? "🎲" : "✏️"}</span><b>{index + 1}번 질문</b>{answers[question.id] ? <Check /> : null}</button>)}</div> : null}
      {active ? <><section className="daily-question-card"><div className="daily-date"><CalendarDays /><span>{active.date} · {active.source === "daily" ? "아침 8시 기본 질문" : active.source === "random" ? "추천 질문" : "선생님 질문"}</span><b>{selected ? "참여 완료 ✓" : role === "teacher" ? "교사 관리" : "한 번만 선택할 수 있어요"}</b>{role === "teacher" ? <div className="tong-question-actions"><button onClick={() => setEditor(active)} aria-label="질문 수정"><Edit3 /></button><button onClick={() => removeQuestion(active)} aria-label="질문 삭제"><Trash2 /></button></div> : null}</div><h2>{active.prompt}</h2><div className="tong-options"><button disabled={!!selected || role === "teacher"} className={selected === "A" ? "selected option-a" : "option-a"} onClick={() => vote("A")}><span>A</span><b>{active.optionA}</b>{selected === "A" ? <Check /> : null}</button><div>VS</div><button disabled={!!selected || role === "teacher"} className={selected === "B" ? "selected option-b" : "option-b"} onClick={() => vote("B")}><span>B</span><b>{active.optionB}</b>{selected === "B" ? <Check /> : null}</button></div>{celebrate ? <div className="tong-confetti"><span>🎉</span><b>오늘도 통했어요!</b><i>✨</i></div> : null}</section>
        {selected ? <section className="tong-results"><div className="tong-section-heading"><div><BarChart3 /><span><b>우리 반 선택 결과</b><small>내 선택: {selected === "A" ? active.optionA : active.optionB}</small></span></div><em>{total}명 참여</em></div><ResultBar label={active.optionA} count={aCount} rate={aRate} /><ResultBar label={active.optionB} count={total - aCount} rate={bRate} second /><div className="matched-friends"><h3>나와 통한 친구들 ⚡ <span>{sameFriends.length}명</span></h3><div>{sameFriends.map((student) => <button key={student.id} onClick={() => setFriend(student)}><span>{student.name.slice(0, 1)}</span><b>{student.name}</b><small>통했어!</small></button>)}</div></div></section> : null}</> : <section className="tong-release-wait"><Clock3 /><h2>오늘의 기본 질문을 준비하고 있어요</h2><p>오전 8시에 새로운 밸런스 질문이 공개됩니다.</p>{role === "teacher" ? <button onClick={addRandom}><Plus />지금 추천 질문 추가하기</button> : null}</section>}</> : <Ranking ranking={ranking} classmates={classmates} onFriend={setFriend} />}
    {editor ? <div className="tong-popup-backdrop" onClick={() => setEditor(undefined)}><form className="tong-question-editor" onSubmit={saveQuestion} onClick={(event) => event.stopPropagation()}><button type="button" onClick={() => setEditor(undefined)} aria-label="닫기"><X /></button><p>TEACHER QUESTION</p><h2>{editor === "new" ? "새 질문 직접 만들기" : "질문 내용 수정"}</h2><label>질문<input name="prompt" required defaultValue={editor === "new" ? "" : editor.prompt} placeholder="예: 쉬는 시간에 더 하고 싶은 것은?" /></label><div><label>선택지 A<input name="optionA" required defaultValue={editor === "new" ? "" : editor.optionA} placeholder="운동장 놀기 ⚽" /></label><label>선택지 B<input name="optionB" required defaultValue={editor === "new" ? "" : editor.optionB} placeholder="교실에서 쉬기 📚" /></label></div><button className="save-question">{editor === "new" ? "질문 등록하기" : "수정 내용 저장하기"}</button></form></div> : null}
    {friend && match ? <div className="tong-popup-backdrop" onClick={() => setFriend(undefined)}><div className="tong-match-popup" onClick={(event) => event.stopPropagation()}><button onClick={() => setFriend(undefined)} aria-label="닫기"><X /></button><div className="match-bolt">⚡</div><span className="match-avatar">{friend.name.slice(0, 1)}</span><h2>나랑 {match.matchCount}번 통했어요!</h2><p>{friend.name} 친구와 함께 답한 {match.totalQuestions}개 질문 중<br/><b>{match.matchRate}%</b> 같은 선택을 했어요.</p></div></div> : null}
  </div>;
}

function ResultBar({ label, count, rate, second = false }: { label: string; count: number; rate: number; second?: boolean }) { return <div className={`tong-result-row ${second ? "b" : ""}`}><span><b>{label}</b><em>{count}명 · {rate}%</em></span><i><u style={{ width: `${rate}%` }} /></i></div>; }
function Ranking({ ranking, classmates, onFriend }: { ranking: ReturnType<typeof buildChemistryRanking>; classmates: TongStudent[]; onFriend: (student?: TongStudent) => void }) { return <section className="chemistry-board"><div className="tong-section-heading"><div><Trophy /><span><b>나와 가장 잘 통하는 친구</b><small>함께 답한 질문을 기준으로 계산했어요.</small></span></div></div><div className="chemistry-list">{ranking.map((item, index) => <button key={item.targetUserId} className={index < 3 ? `top rank-${index + 1}` : ""} onClick={() => onFriend(classmates.find((student) => student.id === item.targetUserId))}><em>{index < 3 ? ["🥇", "🥈", "🥉"][index] : index + 1}</em><span className="rank-avatar">{item.targetUserName.slice(0, 1)}</span><span><b>{item.targetUserName}</b><small>{index === 0 ? "영혼의 단짝 👑" : index === 1 ? "마음이 척척 🤝" : index === 2 ? "통하는 사이 ⚡" : `${item.totalQuestions}개 질문 비교`}</small></span><span className="rank-score"><b>{item.matchCount}번</b><small>{item.matchRate}% 통했어요</small></span><ChevronRight /></button>)}</div></section>; }
