"use client";
import { useEffect,useMemo,useState } from "react";
import { BarChart3,CalendarDays,Check,ChevronRight,Edit3,Plus,Shuffle,Sparkles,Trash2,Trophy,X,Zap } from "lucide-react";
import { buildChemistryRanking,calculateMatchCount } from "@/lib/tong/calculate-match-count";
import { recordPointActivity } from "@/lib/my-room/points";
import type { DailyQuestion,TongOption,TongStudent,UserVote } from "@/types/tong";

const pool=[["탕수육은 어떻게 먹는 게 좋아?","부먹 🥣","찍먹 🥢"],["초능력을 가진다면?","순간이동 ⚡","시간여행 ⏰"],["주말 날씨로 더 좋은 것은?","눈 오는 날 ❄️","비 오는 날 ☔"],["학교가 끝난 뒤에는?","친구와 운동하기 ⚽","집에서 게임하기 🎮"],["여행을 떠난다면?","계획대로 차근차근 🗺️","마음 가는 대로 🚲"],["간식 하나만 고른다면?","아이스크림 🍦","감자칩 🍟"],["하루 동안 살아 본다면?","하늘을 나는 새 🕊️","바다를 누비는 돌고래 🐬"]] as const;
function hash(value:string){let result=0;for(const char of value)result=(result*31+char.charCodeAt(0))>>>0;return result}
function makeQuestion(date:string,seed:string,source:DailyQuestion["source"]):DailyQuestion{const item=pool[hash(seed)%pool.length];return{id:`tong-${source}-${seed}`,date,prompt:item[0],optionA:item[1],optionB:item[2],source,createdAt:new Date().toISOString()}}
function previousDate(today:string,offset:number){const date=new Date(`${today}T12:00:00+09:00`);date.setDate(date.getDate()-offset);return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul"}).format(date)}
function history(students:TongStudent[],today:string):UserVote[]{return Array.from({length:14},(_,index)=>makeQuestion(previousDate(today,index+1),previousDate(today,index+1),"daily")).flatMap(question=>students.map(student=>({userId:student.id,questionId:question.id,selectedOption:(hash(`${student.id}-${question.id}`)%2?"A":"B") as TongOption,votedAt:`${question.date}T09:00:00+09:00`})))}

export function TongCenter({currentUser,students,role,today}:{currentUser:TongStudent;students:TongStudent[];role:"teacher"|"student";today:string}){
  const classmates=students.length?students:[currentUser],storeKey=`moduboard:tong:questions:${today}`,daily=makeQuestion(today,today,"daily");
  const [questions,setQuestions]=useState<DailyQuestion[]>([daily]),[activeId,setActiveId]=useState(daily.id),[answers,setAnswers]=useState<Record<string,TongOption>>({}),[tab,setTab]=useState<"today"|"ranking">("today"),[friend,setFriend]=useState<TongStudent>(),[celebrate,setCelebrate]=useState(false),[editor,setEditor]=useState<DailyQuestion|"new">();
  const active=questions.find(question=>question.id===activeId)??questions[0];
  useEffect(()=>{const saved=localStorage.getItem(storeKey);if(saved)try{const parsed=JSON.parse(saved) as DailyQuestion[],merged=parsed.some(question=>question.source==="daily")?parsed:[daily,...parsed];setQuestions(merged);setActiveId(merged[0]?.id??daily.id)}catch{}},[storeKey]);
  useEffect(()=>{const loaded:Record<string,TongOption>={};for(const question of questions){const value=localStorage.getItem(`moduboard:tong:${currentUser.id}:${question.id}`);if(value==="A"||value==="B")loaded[question.id]=value}setAnswers(current=>({...current,...loaded}))},[currentUser.id,questions]);
  useEffect(()=>{const tomorrow=previousDate(today,-1),next=Date.parse(`${tomorrow}T00:00:00+09:00`),timer=window.setTimeout(()=>window.location.reload(),Math.max(1000,next-Date.now()));return()=>window.clearTimeout(timer)},[today]);
  const oldVotes=useMemo(()=>history(classmates,today),[classmates,today]),todayVotes=useMemo<UserVote[]>(()=>questions.flatMap(question=>{const simulated=classmates.filter(student=>student.id!==currentUser.id).map(student=>({userId:student.id,questionId:question.id,selectedOption:(hash(`${student.id}-${question.id}`)%2?"A":"B") as TongOption,votedAt:new Date().toISOString()}));return answers[question.id]?[...simulated,{userId:currentUser.id,questionId:question.id,selectedOption:answers[question.id],votedAt:new Date().toISOString()}]:simulated}),[answers,classmates,currentUser.id,questions]),allVotes=useMemo(()=>[...oldVotes,...todayVotes],[oldVotes,todayVotes]),ranking=useMemo(()=>buildChemistryRanking(currentUser.id,classmates,allVotes),[allVotes,classmates,currentUser.id]);
  const selected=active?answers[active.id]:undefined,activeVotes=active?todayVotes.filter(vote=>vote.questionId===active.id):[],aCount=activeVotes.filter(vote=>vote.selectedOption==="A").length,total=activeVotes.length,aRate=total?Math.round(aCount/total*100):0,sameFriends=active&&selected?classmates.filter(student=>student.id!==currentUser.id&&activeVotes.some(vote=>vote.userId===student.id&&vote.selectedOption===selected)):[],match=friend?calculateMatchCount(currentUser.id,friend.id,allVotes):null;
  function persist(next:DailyQuestion[]){setQuestions(next);setActiveId(current=>next.some(question=>question.id===current)?current:next[0]?.id??"");localStorage.setItem(storeKey,JSON.stringify(next))}
  function vote(option:TongOption){if(!active||selected||role!=="student")return;localStorage.setItem(`moduboard:tong:${currentUser.id}:${active.id}`,option);setAnswers(current=>({...current,[active.id]:option}));recordPointActivity(currentUser.id,"vote",active.id);setCelebrate(true);setTimeout(()=>setCelebrate(false),1500)}
  function addRandom(){const question=makeQuestion(today,`${Date.now()}`,"random");persist([...questions,question]);setActiveId(question.id)}
  function saveQuestion(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),prompt=String(form.get("prompt")||"").trim(),optionA=String(form.get("optionA")||"").trim(),optionB=String(form.get("optionB")||"").trim();if(!prompt||!optionA||!optionB)return;if(editor==="new"){const question:DailyQuestion={id:`tong-teacher-${crypto.randomUUID()}`,date:today,prompt,optionA,optionB,source:"teacher",createdAt:new Date().toISOString()};persist([...questions,question]);setActiveId(question.id)}else if(editor)persist(questions.map(question=>question.id===editor.id?{...question,prompt,optionA,optionB}:question));setEditor(undefined)}
  return <div className="tong-center"><header className="tong-hero"><div><p><Sparkles/>DAILY CHEMISTRY</p><h1>모두의 통</h1><span>매일 자정, 친구들과 통하는 새로운 밸런스 질문을 만나요.</span></div><div className="tong-streak"><b>하루 한 번만 선택 가능</b><span>선택한 답은 바꿀 수 없어요.</span></div></header><nav className="tong-tabs"><button className={tab==="today"?"active":""} onClick={()=>setTab("today")}><Zap/>오늘의 밸런스</button><button className={tab==="ranking"?"active":""} onClick={()=>setTab("ranking")}><Trophy/>우리 반 케미 랭킹</button></nav>
    {tab==="today"?<><div className="tong-question-toolbar"><div><b>오늘의 질문</b><span>{questions.length}개</span></div>{role==="teacher"?<div><button onClick={addRandom}><Shuffle/>추천 질문 추가</button><button className="primary" onClick={()=>setEditor("new")}><Plus/>직접 만들기</button></div>:null}</div><div className="tong-question-chips">{questions.map((question,index)=><button className={question.id===active?.id?"active":""} key={question.id} onClick={()=>setActiveId(question.id)}><span>{question.source==="daily"?"🌙":question.source==="random"?"🎲":"🧑‍🏫"}</span><b>{index+1}번 질문</b>{answers[question.id]?<Check/>:null}</button>)}</div>{active?<><section className="daily-question-card"><div className="daily-date"><CalendarDays/><span>{active.date} · {active.source==="daily"?"자정 기본 질문":"선생님 추가 질문"}</span><b>{selected?"참여 완료 ✅":role==="teacher"?"교사 관리":"한 번만 선택할 수 있어요"}</b>{role==="teacher"?<div className="tong-question-actions"><button onClick={()=>setEditor(active)} aria-label="질문 수정"><Edit3/></button><button onClick={()=>confirm("질문을 삭제할까요?")&&persist(questions.filter(question=>question.id!==active.id))} aria-label="질문 삭제"><Trash2/></button></div>:null}</div><h2>{active.prompt}</h2><div className="tong-options"><button disabled={!!selected||role==="teacher"} className={selected==="A"?"selected option-a":"option-a"} onClick={()=>vote("A")}><span>A</span><b>{active.optionA}</b>{selected==="A"?<Check/>:null}</button><div>VS</div><button disabled={!!selected||role==="teacher"} className={selected==="B"?"selected option-b":"option-b"} onClick={()=>vote("B")}><span>B</span><b>{active.optionB}</b>{selected==="B"?<Check/>:null}</button></div>{celebrate?<div className="tong-confetti"><span>🎉</span><b>오늘도 통했어요!</b><i>⚡</i></div>:null}</section>{selected?<section className="tong-results"><div className="tong-section-heading"><div><BarChart3/><span><b>우리 반 선택 결과</b><small>내 선택: {selected==="A"?active.optionA:active.optionB}</small></span></div><em>{total}명 참여</em></div><ResultBar label={active.optionA} count={aCount} rate={aRate}/><ResultBar label={active.optionB} count={total-aCount} rate={100-aRate} second/><div className="matched-friends"><h3>나와 통한 친구들 ⚡ <span>{sameFriends.length}명</span></h3><div>{sameFriends.map(student=><button key={student.id} onClick={()=>setFriend(student)}><span>{student.name.slice(0,1)}</span><b>{student.name}</b><small>통했어!</small></button>)}</div></div></section>:null}</>:null}</>:<Ranking ranking={ranking} classmates={classmates} onFriend={setFriend}/>} 
    {editor?<div className="tong-popup-backdrop" onClick={()=>setEditor(undefined)}><form className="tong-question-editor" onSubmit={saveQuestion} onClick={event=>event.stopPropagation()}><button type="button" onClick={()=>setEditor(undefined)} aria-label="닫기"><X/></button><p>TEACHER QUESTION</p><h2>{editor==="new"?"새 질문 직접 만들기":"질문 내용 수정"}</h2><label>질문<input name="prompt" required defaultValue={editor==="new"?"":editor.prompt}/></label><div><label>선택지 A<input name="optionA" required defaultValue={editor==="new"?"":editor.optionA}/></label><label>선택지 B<input name="optionB" required defaultValue={editor==="new"?"":editor.optionB}/></label></div><button className="save-question">저장하기</button></form></div>:null}
    {friend&&match?<div className="tong-popup-backdrop" onClick={()=>setFriend(undefined)}><div className="tong-match-popup" onClick={event=>event.stopPropagation()}><button onClick={()=>setFriend(undefined)} aria-label="닫기"><X/></button><div className="match-bolt">⚡</div><span className="match-avatar">{friend.name.slice(0,1)}</span><h2>나랑 {match.matchCount}번 통했어! ⚡</h2><p>{friend.name} 친구와 함께 답한 {match.totalQuestions}개 질문 중<br/><b>{match.matchRate}%</b> 같은 선택을 했어요.</p></div></div>:null}
  </div>
}

function ResultBar({label,count,rate,second=false}:{label:string;count:number;rate:number;second?:boolean}){return <div className={`tong-result-row ${second?"b":""}`}><span><b>{label}</b><em>{count}명 · {rate}%</em></span><i><u style={{width:`${rate}%`}}/></i></div>}
function Ranking({ranking,classmates,onFriend}:{ranking:ReturnType<typeof buildChemistryRanking>;classmates:TongStudent[];onFriend:(student?:TongStudent)=>void}){return <section className="chemistry-board"><div className="tong-section-heading"><div><Trophy/><span><b>나와 가장 많이 통한 친구</b><small>같은 답을 선택한 누적 횟수로 계산해요.</small></span></div></div><div className="chemistry-list">{ranking.map((item,index)=><button key={item.targetUserId} className={index<3?`top rank-${index+1}`:""} onClick={()=>onFriend(classmates.find(student=>student.id===item.targetUserId))}><em>{index<3?["🥇","🥈","🥉"][index]:index+1}</em><span className="rank-avatar">{item.targetUserName.slice(0,1)}</span><span><b>{item.targetUserName}</b><small>{index===0?"영혼의 단짝 👑":index===1?"마음이 척척 🤝":index===2?"통하는 사이 ⚡":`${item.totalQuestions}개 질문 비교`}</small></span><span className="rank-score"><b>{item.matchCount}번</b><small>{item.matchRate}% 통했어요</small></span><ChevronRight/></button>)}</div></section>}
