"use client";
import { useMemo, useState } from "react";
import { BarChart3, CalendarDays, Check, ChevronDown, Plus, Search, ShieldCheck, Trash2, UserCheck, Users, X } from "lucide-react";
import { recordPointActivity } from "@/lib/my-room/points";

export type PollOption = { id: string; text: string };
export type VoteChoice = string;
export type VoteResponse = { studentId: string; studentName: string; choice: VoteChoice; votedAt: string };
export type ClassroomVote = { id: string; title: string; description: string; voteType: "binary" | "custom"; options: PollOption[]; createdAt: string; deadline: string | null; allowAbstain: boolean; isAnonymous: boolean; createdBy: string; responses: VoteResponse[] };
type Student = { id: string; name: string; studentNum: number | null };
const ABSTAIN = "abstain";
const colors = ["#6579d8", "#e76f89", "#4faa82", "#e5a23f", "#8a6ccf", "#4b9fbd", "#d46cba", "#789249"];
const binaryOptions: PollOption[] = [{ id: "agree", text: "찬성" }, { id: "disagree", text: "반대" }];

function remaining(deadline: string | null) { if (!deadline) return "마감 기한 없음"; const diff = new Date(deadline).getTime() - Date.now(); if (diff <= 0) return "마감됨"; const hours = Math.ceil(diff / 3600000); return hours < 24 ? `⏰ 마감까지 ${hours}시간 남음` : `📅 D-${Math.ceil(hours / 24)}`; }
function pollOptions(vote: ClassroomVote) { return [...vote.options, ...(vote.allowAbstain ? [{ id: ABSTAIN, text: "기권" }] : [])]; }

export function VoteCenter({ currentUser, role, students, initialCanCreateVote = false }: { currentUser: Student; role: "teacher" | "student"; students: Student[]; initialCanCreateVote?: boolean }) {
  const seed = students.slice(0,4).map((s,i):VoteResponse=>({studentId:s.id,studentName:s.name,choice:i%3===0?"disagree":"agree",votedAt:new Date().toISOString()}));
  const [votes,setVotes]=useState<ClassroomVote[]>([
    {id:"vote-1",title:"다음 현장체험학습 장소로 어디가 좋을까요?",description:"우리 반이 함께 즐겁게 배울 장소를 결정해요.",voteType:"custom",options:[{id:"museum",text:"과학관"},{id:"forest",text:"숲 체험원"},{id:"palace",text:"역사 박물관"}],createdAt:new Date().toISOString(),deadline:new Date(Date.now()+7200000).toISOString(),allowAbstain:true,isAnonymous:false,createdBy:"선생님",responses:students.slice(0,3).map((s,i)=>({studentId:s.id,studentName:s.name,choice:["museum","forest","museum"][i],votedAt:new Date().toISOString()}))},
    {id:"vote-2",title:"교실에서 실내화를 신는 것에 찬성하나요?",description:"안전하고 깨끗한 교실을 위한 우리 반 투표입니다.",voteType:"binary",options:binaryOptions,createdAt:new Date(Date.now()-172800000).toISOString(),deadline:null,allowAbstain:false,isAnonymous:true,createdBy:"선생님",responses:seed}
  ]);
  const [permission,setPermission]=useState(initialCanCreateVote),[createOpen,setCreateOpen]=useState(false),[detail,setDetail]=useState<ClassroomVote|null>(null),[detailTab,setDetailTab]=useState("agree"),[query,setQuery]=useState(""),[sort,setSort]=useState<"newest"|"oldest">("newest"),[from,setFrom]=useState(""),[to,setTo]=useState("");
  const filtered=useMemo(()=>votes.filter(v=>v.title.toLowerCase().includes(query.toLowerCase())&&(!from||new Date(v.createdAt)>=new Date(from))&&(!to||new Date(v.createdAt)<=new Date(`${to}T23:59:59`))).sort((a,b)=>(sort==="newest"?-1:1)*(new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime())),[votes,query,sort,from,to]);
  function cast(id:string,choice:string){setVotes(all=>all.map(v=>v.id===id?{...v,responses:[...v.responses.filter(r=>r.studentId!==currentUser.id),{studentId:currentUser.id,studentName:currentUser.name,choice,votedAt:new Date().toISOString()}]}:v));recordPointActivity(currentUser.id,"vote",id)}
  function createVote(data:Omit<ClassroomVote,"id"|"createdAt"|"createdBy"|"responses">){setVotes(v=>[{...data,id:crypto.randomUUID(),createdAt:new Date().toISOString(),createdBy:currentUser.name,responses:[]},...v]);setCreateOpen(false)}
  const canCreate=role==="teacher"||permission;
  return <div className="vote-center"><header className="vote-hero"><div><p>우리 반의 생각을 한눈에</p><h1>모두의 투표</h1><span>찬반부터 여러 후보 선택까지 쉽고 즐겁게 결정해요.</span></div><div className="vote-hero-icon"><BarChart3/></div></header>
    {role==="teacher"?<section className="vote-permission"><div><ShieldCheck/><span><b>학생 투표 생성 권한</b><small>허용하면 학생도 새 투표를 만들 수 있어요.</small></span></div><label className="vote-switch"><input type="checkbox" checked={permission} onChange={e=>setPermission(e.target.checked)}/><span/></label></section>:null}
    <section className="vote-toolbar"><label className="vote-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="투표 제목 검색"/></label><label className="vote-date"><CalendarDays/><input type="date" value={from} onChange={e=>setFrom(e.target.value)}/><span>~</span><input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label className="vote-sort"><select value={sort} onChange={e=>setSort(e.target.value as typeof sort)}><option value="newest">최신순</option><option value="oldest">과거순</option></select><ChevronDown/></label>{canCreate?<button className="vote-create-button" onClick={()=>setCreateOpen(true)}><Plus/>새 투표 만들기</button>:null}</section>
    <div className="vote-list-heading"><div><h2>우리 반 투표</h2><p>{filtered.length}개의 투표가 있어요</p></div></div><section className="vote-card-grid">{filtered.map(v=><VoteCard key={v.id} vote={v} currentUser={currentUser} role={role} onVote={cast} onDetail={()=>{setDetail(v);setDetailTab(v.options[0]?.id||ABSTAIN)}}/>)}</section>
    {createOpen?<VoteCreateModal onClose={()=>setCreateOpen(false)} onCreate={createVote}/>:null}{detail?<VoteDetailModal vote={votes.find(v=>v.id===detail.id)??detail} students={students} tab={detailTab} setTab={setDetailTab} onClose={()=>setDetail(null)}/>:null}
  </div>;
}

function VoteCard({vote,currentUser,role,onVote,onDetail}:{vote:ClassroomVote;currentUser:Student;role:"teacher"|"student";onVote:(id:string,c:string)=>void;onDetail:()=>void}){
  const closed=!!vote.deadline&&new Date(vote.deadline).getTime()<=Date.now(),selected=vote.responses.find(r=>r.studentId===currentUser.id)?.choice,options=pollOptions(vote),total=vote.responses.length;
  return <article className="vote-card"><header><span className={closed?"vote-status closed":"vote-status live"}>{closed?"마감됨":"진행 중"}</span><span className="vote-kind">{vote.voteType==="custom"?"다중 선택":"찬반"}</span><span className="vote-remaining">{remaining(vote.deadline)}</span></header><h2>{vote.title}</h2><p>{vote.description}</p><div className={`vote-choice-buttons custom count-${Math.min(options.length,4)}`}>{options.map((o,i)=><button key={o.id} disabled={closed} className={selected===o.id?"selected":o.id} onClick={()=>onVote(vote.id,o.id)}><span>{o.id===ABSTAIN?"✋":`${i+1}`}</span><b>{o.text}</b>{selected===o.id?<Check/>:null}</button>)}</div>{selected||role==="teacher"?<div className="vote-results">{options.map((o,i)=>{const count=vote.responses.filter(r=>r.choice===o.id).length,percent=total?Math.round(count/total*100):0;return <div key={o.id}><div><span>{o.text}</span><b>{percent}% <small>{count}표</small></b></div><i><em style={{width:`${percent}%`,background:colors[i%colors.length]}}/></i></div>})}<p><Users/> 총 {total}명 참여{vote.isAnonymous?" · 무기명 투표":""}</p></div>:<div className="vote-before"><UserCheck/>투표하면 현재 결과를 볼 수 있어요!</div>}{role==="teacher"?<button className="vote-admin-button" onClick={onDetail}><ShieldCheck/>교사 전용: 명부 및 상세 결과 보기</button>:null}</article>
}

function VoteCreateModal({onClose,onCreate}:{onClose:()=>void;onCreate:(v:Omit<ClassroomVote,"id"|"createdAt"|"createdBy"|"responses">)=>void}){
  const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[voteType,setVoteType]=useState<"binary"|"custom">("binary"),[options,setOptions]=useState<PollOption[]>([{id:crypto.randomUUID(),text:"항목 1"},{id:crypto.randomUUID(),text:"항목 2"}]),[allowAbstain,setAllowAbstain]=useState(false),[anonymous,setAnonymous]=useState(false),[noDeadline,setNoDeadline]=useState(false),[deadline,setDeadline]=useState("");
  const valid=title.trim()&&(noDeadline||deadline)&&(voteType==="binary"||options.length>=2&&options.every(o=>o.text.trim()));
  return <div className="vote-modal-backdrop" onClick={onClose}><div className="vote-create-modal" onClick={e=>e.stopPropagation()}><button className="vote-modal-x" onClick={onClose}><X/></button><span className="modal-eyebrow">NEW VOTE</span><h2>새 투표 만들기</h2><div className="vote-type-tabs"><button className={voteType==="binary"?"active":""} onClick={()=>setVoteType("binary")}>👍 찬성 / 반대</button><button className={voteType==="custom"?"active":""} onClick={()=>setVoteType("custom")}>✨ 커스텀 선택지</button></div><label>투표 제목 <b>필수</b><input value={title} onChange={e=>setTitle(e.target.value)} autoFocus placeholder="친구들에게 물어볼 내용을 적어 주세요"/></label><label>설명<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3}/></label>
    {voteType==="custom"?<section className="custom-option-editor"><b>선택지 편집</b>{options.map((o,i)=><div key={o.id}><span>{i+1}</span><input value={o.text} maxLength={60} onChange={e=>setOptions(v=>v.map(x=>x.id===o.id?{...x,text:e.target.value}:x))}/><button disabled={options.length<=2} onClick={()=>setOptions(v=>v.filter(x=>x.id!==o.id))} aria-label="선택지 삭제"><Trash2/></button></div>)}<button onClick={()=>setOptions(v=>[...v,{id:crypto.randomUUID(),text:`항목 ${v.length+1}`}])}><Plus/>선택지 추가</button></section>:null}
    <div className="vote-option-list"><label><span><b>✋ 기권표 허용</b><small>모든 투표 유형에 기권을 추가합니다.</small></span><i className="vote-switch"><input type="checkbox" checked={allowAbstain} onChange={e=>setAllowAbstain(e.target.checked)}/><span/></i></label><label><span><b>🕵️ 무기명 투표</b><small>학생 화면에는 선택 명단을 공개하지 않아요.</small></span><i className="vote-switch"><input type="checkbox" checked={anonymous} onChange={e=>setAnonymous(e.target.checked)}/><span/></i></label></div><label className="deadline-label">마감 일시<input type="datetime-local" value={deadline} disabled={noDeadline} onChange={e=>setDeadline(e.target.value)}/></label><label className="no-deadline"><input type="checkbox" checked={noDeadline} onChange={e=>setNoDeadline(e.target.checked)}/>마감 기한 없음</label><button className="vote-modal-submit" disabled={!valid} onClick={()=>onCreate({title:title.trim(),description:description.trim(),voteType,options:voteType==="binary"?binaryOptions:options.map(o=>({...o,text:o.text.trim()})),allowAbstain,isAnonymous:anonymous,deadline:noDeadline?null:new Date(deadline).toISOString()})}><Plus/>투표 시작하기</button></div></div>
}

function VoteDetailModal({vote,students,tab,setTab,onClose}:{vote:ClassroomVote;students:Student[];tab:string;setTab:(t:string)=>void;onClose:()=>void}){
  const participated=new Set(vote.responses.map(r=>r.studentId)),percent=students.length?(participated.size/students.length*100).toFixed(1):"0.0",tabs=[...pollOptions(vote).map(o=>({key:o.id,label:o.text})),{key:"not-voted",label:"미참여"}],members=tab==="not-voted"?students.filter(s=>!participated.has(s.id)):vote.responses.filter(r=>r.choice===tab).map(r=>({id:r.studentId,name:r.studentName,studentNum:students.find(s=>s.id===r.studentId)?.studentNum??null}));
  return <div className="vote-modal-backdrop" onClick={onClose}><div className="vote-detail-modal" onClick={e=>e.stopPropagation()}><button className="vote-modal-x" onClick={onClose}><X/></button><span className="modal-eyebrow">TEACHER ONLY</span><h2>투표 상세 결과</h2><h3>{vote.title}</h3><div className="participation-box"><div><Users/><span><b>{students.length}명 중 {participated.size}명 참여</b><small>우리 반 참여율</small></span></div><strong>{percent}%</strong><i><em style={{width:`${percent}%`}}/></i></div><div className="vote-detail-tabs">{tabs.map(t=><button key={t.key} className={tab===t.key?"active":""} onClick={()=>setTab(t.key)}>{t.label}<span>{t.key==="not-voted"?students.length-participated.size:vote.responses.filter(r=>r.choice===t.key).length}</span></button>)}</div><div className="student-vote-list">{members.map(s=><div key={s.id}><span>{s.name.slice(0,1)}</span><b>{s.studentNum?`${s.studentNum}번 `:""}{s.name}</b>{tab==="not-voted"?<small>아직 참여하지 않았어요</small>:<Check/>}</div>)}{!members.length?<p>해당하는 학생이 없습니다.</p>:null}</div>{vote.isAnonymous?<div className="anonymous-notice">학생에게는 무기명으로 표시되며, 이 명부는 교사에게만 보입니다.</div>:null}</div></div>
}
