"use client";

import { useMemo, useState } from "react";
import { BarChart3, CalendarDays, Check, ChevronDown, Clock3, Plus, Search, ShieldCheck, Trash2, UserCheck, Users, X } from "lucide-react";
import { recordPointActivity } from "@/lib/my-room/points";

export type PollOption={id:string;text:string};
export type VoteResponse={studentId:string;studentName:string;choice:string;votedAt:string};
export type ClassroomVote={id:string;title:string;description:string;voteType:"binary"|"custom";options:PollOption[];createdAt:string;deadline:string|null;allowAbstain:boolean;isAnonymous:boolean;createdBy:string;responses:VoteResponse[]};
type Student={id:string;name:string;studentNum:number|null};
const ABSTAIN="abstain";
const binaryOptions:PollOption[]=[{id:"agree",text:"찬성"},{id:"disagree",text:"반대"}];
const colors=["#557bd8","#e36e82","#42a27a","#e3a13f","#8666cf","#3c9abb","#d264b0","#7d9348"];

function allOptions(vote:ClassroomVote){return [...vote.options,...(vote.allowAbstain?[{id:ABSTAIN,text:"기권"}]:[])]}
function remaining(deadline:string|null){if(!deadline)return "마감 기한 없음";const diff=new Date(deadline).getTime()-Date.now();if(diff<=0)return "마감됨";const minutes=Math.ceil(diff/60000);if(minutes<60)return `⏰ ${minutes}분 남음`;const hours=Math.ceil(minutes/60);return hours<24?`⏰ ${hours}시간 남음`:`📅 D-${Math.ceil(hours/24)}`}

export function VoteCenter({currentUser,role,students,initialCanCreateVote=false}:{currentUser:Student;role:"teacher"|"student";students:Student[];initialCanCreateVote?:boolean}){
  const seed=students.slice(0,4).map((student,index):VoteResponse=>({studentId:student.id,studentName:student.name,choice:index%3===0?"disagree":"agree",votedAt:new Date().toISOString()}));
  const [votes,setVotes]=useState<ClassroomVote[]>([
    {id:"vote-1",title:"다음 현장체험학습 장소는 어디가 좋을까요?",description:"우리 반이 함께 즐겁게 배우고 싶은 장소를 선택해요.",voteType:"custom",options:[{id:"museum",text:"과학관"},{id:"forest",text:"숲 체험원"},{id:"history",text:"역사 박물관"}],createdAt:new Date().toISOString(),deadline:new Date(Date.now()+7200000).toISOString(),allowAbstain:true,isAnonymous:false,createdBy:"선생님",responses:students.slice(0,3).map((student,index)=>({studentId:student.id,studentName:student.name,choice:["museum","forest","museum"][index],votedAt:new Date().toISOString()}))},
    {id:"vote-2",title:"교실에서 실내화를 신는 것에 찬성하나요?",description:"안전하고 깨끗한 교실을 위한 우리 반 투표입니다.",voteType:"binary",options:binaryOptions,createdAt:new Date(Date.now()-172800000).toISOString(),deadline:null,allowAbstain:false,isAnonymous:true,createdBy:"선생님",responses:seed},
  ]);
  const [studentPermission,setStudentPermission]=useState(initialCanCreateVote),[createOpen,setCreateOpen]=useState(false),[detailVote,setDetailVote]=useState<ClassroomVote|null>(null),[detailTab,setDetailTab]=useState("agree"),[query,setQuery]=useState(""),[sort,setSort]=useState<"newest"|"oldest">("newest"),[from,setFrom]=useState(""),[to,setTo]=useState("");
  const filtered=useMemo(()=>votes.filter(vote=>vote.title.toLowerCase().includes(query.toLowerCase())&&(!from||new Date(vote.createdAt)>=new Date(from))&&(!to||new Date(vote.createdAt)<=new Date(`${to}T23:59:59`))).sort((a,b)=>(sort==="newest"?-1:1)*(new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime())),[votes,query,sort,from,to]);
  const canCreate=role==="teacher"||studentPermission;
  function cast(voteId:string,choice:string){setVotes(current=>current.map(vote=>vote.id!==voteId?vote:{...vote,responses:[...vote.responses.filter(response=>response.studentId!==currentUser.id),{studentId:currentUser.id,studentName:currentUser.name,choice,votedAt:new Date().toISOString()}]}));recordPointActivity(currentUser.id,"vote",voteId)}
  function createVote(vote:Omit<ClassroomVote,"id"|"createdAt"|"createdBy"|"responses">){setVotes(current=>[{...vote,id:crypto.randomUUID(),createdAt:new Date().toISOString(),createdBy:currentUser.name,responses:[]},...current]);setCreateOpen(false)}
  return <div className="vote-center"><header className="vote-hero"><div><p>우리 반의 생각을 한눈에</p><h1>모두의 투표</h1><span>찬반부터 여러 후보 선택까지 쉽고 즐겁게 결정해요.</span></div><div className="vote-hero-icon"><BarChart3/></div></header>
    {role==="teacher"?<section className="vote-permission"><div><ShieldCheck/><span><b>학생 투표 생성 권한</b><small>허용하면 학생도 새 투표를 만들 수 있어요.</small></span></div><Toggle checked={studentPermission} onChange={setStudentPermission} label="학생 투표 생성 허용"/></section>:null}
    <section className="vote-toolbar"><label className="vote-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="투표 제목 검색"/></label><label className="vote-date"><CalendarDays/><input type="date" value={from} onChange={event=>setFrom(event.target.value)}/><span>~</span><input type="date" value={to} onChange={event=>setTo(event.target.value)}/></label><label className="vote-sort"><select value={sort} onChange={event=>setSort(event.target.value as typeof sort)}><option value="newest">최신순</option><option value="oldest">과거순</option></select><ChevronDown/></label>{canCreate?<button className="vote-create-button" onClick={()=>setCreateOpen(true)}><Plus/>새 투표 만들기</button>:null}</section>
    <div className="vote-list-heading"><div><h2>우리 반 투표</h2><p>{filtered.length}개의 투표가 있어요.</p></div></div><section className="vote-card-grid">{filtered.map(vote=><VoteCard key={vote.id} vote={vote} currentUser={currentUser} role={role} onVote={cast} onDetail={()=>{setDetailVote(vote);setDetailTab(vote.options[0]?.id??ABSTAIN)}}/>)}</section>{!filtered.length?<div className="vote-empty"><Search/><h2>조건에 맞는 투표가 없어요</h2><p>검색어나 날짜를 바꾸어 보세요.</p></div>:null}
    {createOpen?<VoteCreateModal onClose={()=>setCreateOpen(false)} onCreate={createVote}/>:null}{detailVote?<VoteDetailModal vote={votes.find(vote=>vote.id===detailVote.id)??detailVote} students={students} tab={detailTab} setTab={setDetailTab} onClose={()=>setDetailVote(null)}/>:null}
  </div>
}

function Toggle({checked,onChange,label}:{checked:boolean;onChange:(value:boolean)=>void;label:string}){return <label className="vote-switch" aria-label={label}><input type="checkbox" checked={checked} onChange={event=>onChange(event.target.checked)}/><span/></label>}

function VoteCard({vote,currentUser,role,onVote,onDetail}:{vote:ClassroomVote;currentUser:Student;role:"teacher"|"student";onVote:(id:string,choice:string)=>void;onDetail:()=>void}){
  const closed=!!vote.deadline&&new Date(vote.deadline).getTime()<=Date.now(),selected=vote.responses.find(response=>response.studentId===currentUser.id)?.choice,options=allOptions(vote),total=vote.responses.length;
  return <article className="vote-card"><header><span className={closed?"vote-status closed":"vote-status live"}>{closed?"마감됨":"진행 중"}</span><span className="vote-kind">{vote.voteType==="custom"?"다중 항목":"찬반"}</span><span className="vote-remaining">{remaining(vote.deadline)}</span></header><h2>{vote.title}</h2><p>{vote.description}</p><div className="vote-choice-buttons custom">{options.map((option,index)=><button key={option.id} disabled={closed} className={selected===option.id?"selected":""} onClick={()=>onVote(vote.id,option.id)}><span>{option.id===ABSTAIN?"✋":index+1}</span><b>{option.text}</b>{selected===option.id?<Check/>:null}</button>)}</div>
    {selected||role==="teacher"?<div className="vote-results">{options.map((option,index)=>{const count=vote.responses.filter(response=>response.choice===option.id).length,percentage=total?Math.round(count/total*100):0;return <div key={option.id}><div><span>{option.text}</span><b>{percentage}% <small>{count}표</small></b></div><i><em style={{width:`${percentage}%`,background:colors[index%colors.length]}}/></i></div>})}<p><Users/>총 {total}명 참여{vote.isAnonymous?" · 무기명 투표":""}</p></div>:<div className="vote-before"><UserCheck/>투표하면 현재 결과를 볼 수 있어요!</div>}
    {role==="teacher"?<button className="vote-admin-button" onClick={onDetail}><ShieldCheck/>교사 전용: 학생 명단과 미참여자 보기</button>:null}</article>
}

function VoteCreateModal({onClose,onCreate}:{onClose:()=>void;onCreate:(vote:Omit<ClassroomVote,"id"|"createdAt"|"createdBy"|"responses">)=>void}){
  const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[voteType,setVoteType]=useState<"binary"|"custom">("binary"),[options,setOptions]=useState<PollOption[]>(()=>[{id:crypto.randomUUID(),text:"항목 1"},{id:crypto.randomUUID(),text:"항목 2"}]),[allowAbstain,setAllowAbstain]=useState(false),[anonymous,setAnonymous]=useState(false),[hasDeadline,setHasDeadline]=useState(true),[deadline,setDeadline]=useState("");
  const customValid=voteType==="binary"||(options.length>=2&&options.every(option=>option.text.trim())),valid=!!title.trim()&&customValid&&(!hasDeadline||!!deadline);
  return <div className="vote-modal-backdrop" onClick={onClose}><div className="vote-create-modal" onClick={event=>event.stopPropagation()}><button className="vote-modal-x" onClick={onClose}><X/></button><span className="modal-eyebrow">NEW VOTE</span><h2>새 투표 만들기</h2><div className="vote-type-tabs"><button className={voteType==="binary"?"active":""} onClick={()=>setVoteType("binary")}>👍 찬성 · 반대</button><button className={voteType==="custom"?"active":""} onClick={()=>setVoteType("custom")}>✨ 커스텀 다중 항목</button></div><label>투표 제목 <b>필수</b><input value={title} onChange={event=>setTitle(event.target.value)} autoFocus maxLength={100} placeholder="친구들에게 물어볼 내용을 적어 주세요"/></label><label>설명<textarea value={description} onChange={event=>setDescription(event.target.value)} rows={3} placeholder="투표에 필요한 설명을 적어 주세요"/></label>
    {voteType==="custom"?<section className="custom-option-editor"><b>선택지 편집</b>{options.map((option,index)=><div key={option.id}><span>{index+1}</span><input value={option.text} maxLength={60} onChange={event=>setOptions(current=>current.map(item=>item.id===option.id?{...item,text:event.target.value}:item))}/><button disabled={options.length<=2} onClick={()=>setOptions(current=>current.filter(item=>item.id!==option.id))} aria-label={`${option.text} 삭제`}><Trash2/></button></div>)}<button onClick={()=>setOptions(current=>[...current,{id:crypto.randomUUID(),text:`항목 ${current.length+1}`}])}><Plus/>선택지 추가</button></section>:null}
    <div className="vote-option-list"><label><span><b>✋ 기권표 허용</b><small>선택지에 기권을 추가해요.</small></span><Toggle checked={allowAbstain} onChange={setAllowAbstain} label="기권표 허용"/></label><label><span><b>🕵️ 무기명 투표</b><small>학생에게 친구들의 선택 명단을 숨겨요.</small></span><Toggle checked={anonymous} onChange={setAnonymous} label="무기명 투표"/></label><label><span><b>⏰ 마감 기한 사용</b><small>끄면 기한 없이 계속 참여할 수 있어요.</small></span><Toggle checked={hasDeadline} onChange={setHasDeadline} label="마감 기한 사용"/></label></div>{hasDeadline?<label className="deadline-label">마감 일시<input type="datetime-local" value={deadline} min={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)} onChange={event=>setDeadline(event.target.value)}/></label>:<div className="deadline-off"><Clock3/>마감 기한 없이 진행합니다.</div>}
    <button className="vote-modal-submit" disabled={!valid} onClick={()=>onCreate({title:title.trim(),description:description.trim(),voteType,options:voteType==="binary"?binaryOptions:options.map(option=>({...option,text:option.text.trim()})),allowAbstain,isAnonymous:anonymous,deadline:hasDeadline?new Date(deadline).toISOString():null})}><Plus/>투표 시작하기</button></div></div>
}

function VoteDetailModal({vote,students,tab,setTab,onClose}:{vote:ClassroomVote;students:Student[];tab:string;setTab:(tab:string)=>void;onClose:()=>void}){
  const participated=new Set(vote.responses.map(response=>response.studentId)),participation=students.length?Number((participated.size/students.length*100).toFixed(1)):0,tabs=[...allOptions(vote).map(option=>({key:option.id,label:option.text})),{key:"not-voted",label:"미참여"}],members=tab==="not-voted"?students.filter(student=>!participated.has(student.id)):vote.responses.filter(response=>response.choice===tab).map(response=>({id:response.studentId,name:response.studentName,studentNum:students.find(student=>student.id===response.studentId)?.studentNum??null}));
  return <div className="vote-modal-backdrop" onClick={onClose}><div className="vote-detail-modal" onClick={event=>event.stopPropagation()}><button className="vote-modal-x" onClick={onClose}><X/></button><span className="modal-eyebrow">TEACHER ONLY</span><h2>투표 상세 결과</h2><h3>{vote.title}</h3><div className="participation-box"><div><Users/><span><b>{students.length}명 중 {participated.size}명 참여</b><small>우리 반 참여율</small></span></div><strong>{participation}%</strong><i><em style={{width:`${participation}%`}}/></i></div><div className="vote-detail-tabs">{tabs.map(item=><button key={item.key} className={tab===item.key?"active":""} onClick={()=>setTab(item.key)}>{item.label}<span>{item.key==="not-voted"?students.length-participated.size:vote.responses.filter(response=>response.choice===item.key).length}</span></button>)}</div><div className="student-vote-list">{members.map(student=><div key={student.id}><span>{student.name.slice(0,1)}</span><b>{student.studentNum?`${student.studentNum}번 `:""}{student.name}</b>{tab==="not-voted"?<small>아직 참여하지 않았어요</small>:<Check/>}</div>)}{!members.length?<p>해당하는 학생이 없습니다.</p>:null}</div>{vote.isAnonymous?<div className="anonymous-notice">학생 화면에는 무기명으로 표시되지만, 생활지도를 위해 담당 교사는 전체 명단을 확인할 수 있습니다.</div>:null}</div></div>
}
