"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Plus,Settings2,Sparkles,Trash2,X} from "lucide-react";
import type {WordCloudMask,WordCloudSession,WordSubmission} from "@/types/word-cloud";

const masks:{id:WordCloudMask;label:string;emoji:string}[]=[{id:"heart",label:"하트",emoji:"❤️"},{id:"cloud",label:"구름",emoji:"☁️"},{id:"star",label:"별",emoji:"⭐"},{id:"circle",label:"동그라미",emoji:"🔵"},{id:"text",label:"글자",emoji:"가"}];
const colors=["#6556c7","#e06488","#3c9b7b","#df9239","#4a8bbd","#9a61b8","#db6c57"];
const seeds:WordSubmission[]=[{id:"seed-1",userId:"seed-1",userName:"민지",text:"즐거움",createdAt:"2026-01-01"},{id:"seed-2",userId:"seed-2",userName:"준호",text:"친구",createdAt:"2026-01-01"},{id:"seed-3",userId:"seed-3",userName:"서윤",text:"즐거움",createdAt:"2026-01-01"},{id:"seed-4",userId:"seed-4",userName:"하윤",text:"배려",createdAt:"2026-01-01"}];
type Session=Omit<WordCloudSession,"words">;type Box={x:number;y:number;w:number;h:number};

function buildMask(shape:WordCloudMask,text:string){const canvas=document.createElement("canvas");canvas.width=1100;canvas.height=600;const ctx=canvas.getContext("2d")!;ctx.fillStyle="#fff";if(shape==="text"){ctx.textAlign="center";ctx.textBaseline="middle";ctx.font=`900 ${Math.max(150,Math.min(350,760/Math.max(1,text.length)))}px Pretendard,sans-serif`;ctx.fillText(text||"꿈",550,310)}else for(let y=0;y<600;y+=3)for(let x=0;x<1100;x+=3)if(insideShape(shape,x,y))ctx.fillRect(x,y,3,3);return ctx.getImageData(0,0,1100,600).data}
function insideShape(shape:WordCloudMask,x:number,y:number){const nx=(x-550)/440,ny=(y-300)/245;if(shape==="circle")return nx*nx+ny*ny<.9;if(shape==="heart"){const xx=nx*1.12,yy=-ny*1.08+.12;return Math.pow(xx*xx+yy*yy-1,3)-xx*xx*yy*yy*yy<=0}if(shape==="star"){const angle=Math.atan2(ny,nx),radius=Math.hypot(nx,ny),limit=.48+.38*(.5+.5*Math.cos(5*angle));return radius<limit}return ((nx+.4)**2+(ny+.02)**2<.4)||((nx-.15)**2+(ny-.18)**2<.56)||((nx-.52)**2+(ny+.05)**2<.32)||((nx+.08)**2+(ny+.36)**2<.35)}
function masked(data:Uint8ClampedArray,x:number,y:number){const px=Math.max(0,Math.min(1099,Math.round(x))),py=Math.max(0,Math.min(599,Math.round(y)));return data[(py*1100+px)*4+3]>0}
function overlaps(a:Box,b:Box){return a.x<b.x+b.w+7&&a.x+a.w+7>b.x&&a.y<b.y+b.h+5&&a.y+a.h+5>b.y}

function CloudCanvas({words,shape,maskText}:{words:{text:string;value:number}[];shape:WordCloudMask;maskText:string}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext("2d")!;ctx.clearRect(0,0,1100,600);ctx.fillStyle="#fbfaff";ctx.fillRect(0,0,1100,600);const mask=buildMask(shape,maskText),sorted=[...words].sort((a,b)=>b.value-a.value),max=Math.max(1,...sorted.map(word=>word.value)),boxes:Box[]=[];sorted.forEach((word,index)=>{const size=20+Math.sqrt(word.value/max)*62;ctx.font=`850 ${size}px Pretendard,sans-serif`;const width=ctx.measureText(word.text).width;for(let step=0;step<2400;step++){const angle=step*.41+index*1.7,r=2+step*.2,x=550+Math.cos(angle)*r-width/2,y=300+Math.sin(angle)*r+size/3,box={x,y:y-size,w:width,h:size*1.12};const points=[[x,y-size],[x+width,y-size],[x,y],[x+width,y],[x+width/2,y-size/2]];if(x<5||x+width>1095||y-size<5||y>595||points.some(point=>!masked(mask,point[0],point[1]))||boxes.some(item=>overlaps(box,item)))continue;ctx.fillStyle=colors[index%colors.length];ctx.fillText(word.text,x,y);boxes.push(box);break}});if(!words.length){ctx.fillStyle="#8b84a6";ctx.textAlign="center";ctx.font="700 26px Pretendard,sans-serif";ctx.fillText("첫 번째 생각을 기다리고 있어요",550,300);ctx.textAlign="start"}},[maskText,shape,words]);return <canvas ref={ref} width={1100} height={600} aria-label="우리 반 실시간 생각구름"/>}

export function WordCloudCenter({currentUser,role}:{currentUser:{id:string;name:string};role:"teacher"|"student"}){
 const storageKey="moduboard:wordcloud:active",[session,setSession]=useState<Session>({id:"cloud-today",topic:"우리 반 하면 생각나는 단어는?",maxSubmissionsPerStudent:3,maskShape:"heart",maskText:"꿈"}),[submissions,setSubmissions]=useState<WordSubmission[]>(seeds),[input,setInput]=useState(""),[setup,setSetup]=useState(false),[error,setError]=useState(""),[hydrated,setHydrated]=useState(false);
 useEffect(()=>{const load=()=>{const saved=localStorage.getItem(storageKey);if(saved)try{const data=JSON.parse(saved);setSession(data.session);setSubmissions(data.submissions)}catch{}};load();setHydrated(true);addEventListener("storage",load);return()=>removeEventListener("storage",load)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem(storageKey,JSON.stringify({session,submissions}))},[hydrated,session,submissions]);
 const words=useMemo(()=>{const counts=new Map<string,number>();for(const item of submissions){const key=item.text.trim().toLocaleLowerCase("ko-KR");const found=[...counts.keys()].find(value=>value.toLocaleLowerCase("ko-KR")===key);counts.set(found??item.text.trim(),(counts.get(found??item.text.trim())??0)+1)}return [...counts].map(([text,value])=>({text,value})).sort((a,b)=>b.value-a.value)},[submissions]);
 const mine=submissions.filter(item=>item.userId===currentUser.id).length,limit=session.maxSubmissionsPerStudent,remaining=limit===0?null:Math.max(0,limit-mine);
 function submit(){const text=input.trim().replace(/\s+/g," ");if(!text)return setError("단어 또는 짧은 문구를 입력해 주세요.");if(text.length>20)return setError("20자 이내로 입력해 주세요.");if(remaining===0)return setError("제출할 수 있는 개수를 모두 사용했어요.");setSubmissions(current=>[...current,{id:crypto.randomUUID(),userId:currentUser.id,userName:currentUser.name,text,createdAt:new Date().toISOString()}]);setInput("");setError("")}
 return <div className="wordcloud-page"><header className="wordcloud-hero"><div><span><Sparkles/>LIVE CLASS CLOUD</span><h1>모두의 생각구름</h1><p>친구들의 생각이 모일수록 같은 단어가 크고 선명하게 자라나요.</p></div>{role==="teacher"?<button onClick={()=>setSetup(true)}><Settings2/>주제와 모양 설정</button>:null}</header>
 <section className="wordcloud-topic"><div><small>오늘의 주제</small><h2>{session.topic}</h2><p>{limit===0?"제출 횟수 제한 없음":`한 사람당 최대 ${limit}개 제출`}</p></div><span>{session.maskShape==="text"?session.maskText:masks.find(mask=>mask.id===session.maskShape)?.emoji}</span></section>
 <section className="wordcloud-stage"><div className={`wordcloud-mask ${session.maskShape}`}><CloudCanvas words={words} shape={session.maskShape} maskText={session.maskText??"꿈"}/></div><aside><h3>내 생각 보내기</h3><p>같은 생각이 여러 번 들어오면 생각구름에서 더 크게 보여요.</p><div className="word-submit"><input value={input} onChange={event=>setInput(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")submit()}} placeholder="단어 또는 짧은 문구" maxLength={20}/><button onClick={submit} disabled={remaining===0}><Plus/>보내기</button></div><div className="submission-meter"><b>{remaining===null?"제한 없이 제출 가능":remaining===0?"제출 완료!":`${remaining}개 더 제출할 수 있어요`}</b><span>{mine}개 제출</span></div>{error?<p className="word-error">{error}</p>:null}<div className="my-words">{submissions.filter(item=>item.userId===currentUser.id).map(item=><span key={item.id}>{item.text}</span>)}</div></aside></section>
 <section className="word-frequency"><div><h3>실시간 인기 생각</h3><span>총 {submissions.length}개의 생각</span></div>{words.slice(0,8).map((word,index)=><article key={word.text}><b>{index+1}</b><span>{word.text}</span><em>{word.value}번</em><i><small style={{width:`${Math.round(word.value/Math.max(1,words[0]?.value??1)*100)}%`}}/></i>{role==="teacher"?<button onClick={()=>setSubmissions(current=>current.filter(item=>item.text!==word.text))} aria-label={`${word.text} 삭제`}><Trash2/></button>:null}</article>)}</section>
 {setup?<Setup session={session} onClose={()=>setSetup(false)} onSave={next=>{setSession(next);setSetup(false)}}/>:null}</div>
}

function Setup({session,onClose,onSave}:{session:Session;onClose:()=>void;onSave:(session:Session)=>void}){const [topic,setTopic]=useState(session.topic),[limit,setLimit]=useState<0|1|3>(session.maxSubmissionsPerStudent),[shape,setShape]=useState(session.maskShape),[maskText,setMaskText]=useState(session.maskText??"꿈");return <div className="wordcloud-modal-backdrop" onClick={onClose}><div className="wordcloud-modal" onClick={event=>event.stopPropagation()}><button className="wordcloud-x" onClick={onClose}><X/></button><small>TEACHER SETUP</small><h2>생각구름 설정</h2><label>질문 또는 주제<input value={topic} onChange={event=>setTopic(event.target.value)} maxLength={100}/></label><label>학생 1인당 제출 횟수<select value={limit} onChange={event=>setLimit(Number(event.target.value) as 0|1|3)}><option value={1}>1개</option><option value={3}>최대 3개</option><option value={0}>제한 없음</option></select></label><fieldset><legend>생각구름 모양</legend><div>{masks.map(mask=><button type="button" key={mask.id} className={shape===mask.id?"active":""} onClick={()=>setShape(mask.id)}><span>{mask.emoji}</span><b>{mask.label}</b></button>)}</div></fieldset>{shape==="text"?<label>모양으로 사용할 글자<input value={maskText} onChange={event=>setMaskText(event.target.value.slice(0,4))} placeholder="예: 꿈, 우리반" maxLength={4}/></label>:null}<button className="wordcloud-save" disabled={!topic.trim()||(shape==="text"&&!maskText.trim())} onClick={()=>onSave({...session,topic:topic.trim(),maxSubmissionsPerStudent:limit,maskShape:shape,maskText:maskText.trim()||"꿈"})}>설정 적용하기</button></div></div>}
