"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { Cloud, Plus, Settings2, Sparkles, Trash2, X } from "lucide-react";
import type { WordCloudMask, WordCloudSession, WordSubmission } from "@/types/word-cloud";

const masks:{id:WordCloudMask;label:string;emoji:string}[]=[{id:"heart",label:"하트",emoji:"❤️"},{id:"cloud",label:"구름",emoji:"☁️"},{id:"star",label:"별",emoji:"⭐"},{id:"circle",label:"동그라미",emoji:"🟣"}];
const palette=["#6556c7","#e06488","#3c9b7b","#df9239","#4a8bbd","#9a61b8","#db6c57"];
type Box={x:number;y:number;w:number;h:number};

function insideMask(shape:WordCloudMask,x:number,y:number){const nx=(x-550)/440,ny=(y-300)/245;if(shape==="circle")return nx*nx+ny*ny<.92;if(shape==="heart"){const xx=nx*1.12,yy=-ny*1.08+.12;return Math.pow(xx*xx+yy*yy-1,3)-xx*xx*yy*yy*yy<=0}if(shape==="star"){const a=Math.atan2(ny,nx),r=Math.hypot(nx,ny),limit=.48+.38*(.5+.5*Math.cos(5*a));return r<limit}return ((nx+.38)**2+(ny+.02)**2<.43)||((nx-.18)**2+(ny-.18)**2<.55)||((nx-.52)**2+(ny+.05)**2<.34)||((nx+.1)**2+(ny+.35)**2<.35)}
function overlaps(a:Box,b:Box){return a.x<b.x+b.w+8&&a.x+a.w+8>b.x&&a.y<b.y+b.h+6&&a.y+a.h+6>b.y}

function WordCloudCanvas({words,shape}:{words:{text:string;value:number}[];shape:WordCloudMask}){
  const ref=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext("2d")!;ctx.clearRect(0,0,1100,600);ctx.fillStyle="#fbfaff";ctx.fillRect(0,0,1100,600);const sorted=[...words].sort((a,b)=>b.value-a.value),max=Math.max(1,...sorted.map(w=>w.value)),boxes:Box[]=[];sorted.forEach((word,index)=>{const size=24+Math.sqrt(word.value/max)*58;ctx.font=`800 ${size}px Pretendard, sans-serif`;const width=ctx.measureText(word.text).width;for(let step=0;step<1800;step++){const angle=step*.43+index*.9,r=3+step*.22,x=550+Math.cos(angle)*r-width/2,y=300+Math.sin(angle)*r+size/3,box={x,y:y-size,w:width,h:size*1.15};if(x<10||x+width>1090||y-size<8||y>592||!insideMask(shape,x,y-size/2)||!insideMask(shape,x+width,y-size/2)||boxes.some(b=>overlaps(box,b)))continue;ctx.fillStyle=palette[index%palette.length];ctx.fillText(word.text,x,y);boxes.push(box);break}});if(!words.length){ctx.fillStyle="#8b84a6";ctx.textAlign="center";ctx.font="700 26px Pretendard, sans-serif";ctx.fillText("첫 번째 생각을 기다리고 있어요!",550,300);ctx.textAlign="start"}},[words,shape]);
  return <canvas ref={ref} width={1100} height={600} aria-label="우리 반 실시간 생각구름"/>;
}

export function WordCloudCenter({currentUser,role}:{currentUser:{id:string;name:string};role:"teacher"|"student"}){
  const [session,setSession]=useState<Omit<WordCloudSession,"words">>({id:"cloud-today",topic:"우리 반 하면 생각나는 단어는?",maxSubmissionsPerStudent:3,maskShape:"heart"});
  const [submissions,setSubmissions]=useState<WordSubmission[]>([{id:"1",userId:"seed1",userName:"민지",text:"즐거움",createdAt:new Date().toISOString()},{id:"2",userId:"seed2",userName:"준호",text:"친구",createdAt:new Date().toISOString()},{id:"3",userId:"seed3",userName:"서윤",text:"즐거움",createdAt:new Date().toISOString()},{id:"4",userId:"seed4",userName:"도윤",text:"배려",createdAt:new Date().toISOString()}]);
  const [input,setInput]=useState(""),[setup,setSetup]=useState(false),[error,setError]=useState("");
  const words=useMemo(()=>{const counts=new Map<string,number>();submissions.forEach(s=>{const key=s.text.trim();counts.set(key,(counts.get(key)||0)+1)});return [...counts].map(([text,value])=>({text,value})).sort((a,b)=>b.value-a.value)},[submissions]);
  const mine=submissions.filter(s=>s.userId===currentUser.id).length,limit=session.maxSubmissionsPerStudent,remaining=limit===0?null:Math.max(0,limit-mine);
  function submit(){const text=input.trim().replace(/\s+/g," ");if(!text){setError("단어나 짧은 문구를 입력해 주세요.");return}if(text.length>24){setError("24자 이내로 입력해 주세요.");return}if(remaining===0){setError("제출할 수 있는 개수를 모두 사용했어요.");return}setSubmissions(v=>[...v,{id:crypto.randomUUID(),userId:currentUser.id,userName:currentUser.name,text,createdAt:new Date().toISOString()}]);setInput("");setError("")}
  return <div className="wordcloud-page"><header className="wordcloud-hero"><div><span><Sparkles/> LIVE CLASS CLOUD</span><h1>모두의 생각구름</h1><p>친구들의 생각이 모일수록 같은 단어가 크고 선명하게 자라나요.</p></div>{role==="teacher"?<button onClick={()=>setSetup(true)}><Settings2/>주제와 모양 설정</button>:null}</header>
    <section className="wordcloud-topic"><div><small>오늘의 주제</small><h2>{session.topic}</h2><p>{limit===0?"제출 횟수 제한 없음":`한 사람당 최대 ${limit}개 제출`}</p></div><span>{masks.find(m=>m.id===session.maskShape)?.emoji}</span></section>
    <section className="wordcloud-stage"><div className={`wordcloud-mask ${session.maskShape}`}><WordCloudCanvas words={words} shape={session.maskShape}/></div><aside><h3>내 생각 보내기</h3><p>같은 생각이 여러 번 나오면 생각구름에서 더 크게 보여요.</p><div className="word-submit"><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")submit()}} placeholder="단어 또는 짧은 문구" maxLength={24}/><button onClick={submit} disabled={remaining===0}><Plus/>보내기</button></div><div className="submission-meter"><b>{remaining===null?"제한 없이 제출 가능":remaining===0?"제출 완료!":`${remaining}개 더 제출할 수 있어요`}</b><span>{mine}개 제출</span></div>{error?<p className="word-error">{error}</p>:null}<div className="my-words">{submissions.filter(s=>s.userId===currentUser.id).map(s=><span key={s.id}>{s.text}{role==="teacher"?<button onClick={()=>setSubmissions(v=>v.filter(x=>x.id!==s.id))}><X/></button>:null}</span>)}</div></aside></section>
    <section className="word-frequency"><div><h3>실시간 인기 생각</h3><span>총 {submissions.length}개의 생각</span></div>{words.slice(0,8).map((w,i)=><article key={w.text}><b>{i+1}</b><span>{w.text}</span><em>{w.value}번</em><i><small style={{width:`${Math.round(w.value/Math.max(1,words[0]?.value||1)*100)}%`}}/></i>{role==="teacher"?<button onClick={()=>setSubmissions(v=>v.filter(s=>s.text!==w.text))} aria-label={`${w.text} 삭제`}><Trash2/></button>:null}</article>)}</section>
    {setup?<WordCloudSetup session={session} onClose={()=>setSetup(false)} onSave={next=>{setSession(next);setSetup(false)}}/>:null}
  </div>
}

function WordCloudSetup({session,onClose,onSave}:{session:Omit<WordCloudSession,"words">;onClose:()=>void;onSave:(s:Omit<WordCloudSession,"words">)=>void}){const [topic,setTopic]=useState(session.topic),[limit,setLimit]=useState(session.maxSubmissionsPerStudent),[shape,setShape]=useState(session.maskShape);return <div className="wordcloud-modal-backdrop" onClick={onClose}><div className="wordcloud-modal" onClick={e=>e.stopPropagation()}><button className="wordcloud-x" onClick={onClose}><X/></button><small>TEACHER SETUP</small><h2>생각구름 설정</h2><label>질문 또는 주제<input value={topic} onChange={e=>setTopic(e.target.value)} maxLength={100}/></label><label>학생 1인당 제출 개수<select value={limit} onChange={e=>setLimit(Number(e.target.value))}><option value={1}>1개</option><option value={2}>최대 2개</option><option value={3}>최대 3개</option><option value={5}>최대 5개</option><option value={0}>제한 없음</option></select></label><fieldset><legend>생각구름 모양</legend><div>{masks.map(m=><button key={m.id} className={shape===m.id?"active":""} onClick={()=>setShape(m.id)}><span>{m.emoji}</span><b>{m.label}</b></button>)}</div></fieldset><button className="wordcloud-save" disabled={!topic.trim()} onClick={()=>onSave({...session,topic:topic.trim(),maxSubmissionsPerStudent:limit,maskShape:shape})}>설정 적용하기</button></div></div>}
